### ISSUE TITLE
Custom report

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#10]
- [x] I will send you an example table of the report we would need to produce quickly for each country.

- [x] Could you then develop this report?

**Comment by abyot** [comment]
Country report is now available together with data entry. See the green "Country report" button

![image](https://cloud.githubusercontent.com/assets/4967749/19440043/adffc026-9480-11e6-9785-6e52d91fb25a.png)

It allows to download in PDF and excel formats

**Comment by chloedenavit** [comment]
Thanks Abyot. I think this will be very useful for users to print their data and review which questions they have answered. 

Could you rename the green button to say "View data as tables" instead of country report?

**Comment by abyot** [comment]
sure, will change it.

**Comment by Alisia1** [comment]
Could you please change the name as  "View data as tables" ? I still see the old name..thanks!

**Comment by abyot** [comment]
Changed. To see the effect just refresh your browser.
