### ISSUE TITLE
summary report

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#100]
@abyot, in the Report tab, could you please: 
1) List Reports Types at the bottom (below agency)
2) Set Summary Report as the default option that comes up

I know they will have to click on the button to generate, but I'd like the Report Type to be selected automatically so they have to only click on  one button to review their entered data and then click on Mark Complete.

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
Perfect, thanks.
