### ISSUE TITLE
Moving tables in the dashboard

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#101]
Hi @abyot,
When we drag tables in the dashboard app of the inventory to a different position, they seem to move back up to their original position and we cannot succeed in moving them. Nicolas could not do it on his computer either. 
Could you tell us if there is another setting we need to modify?
Thanks!

**Comment by abyot** [comment]
No, there is no setting. The thing is the place you are  going to move into should be the same size as the table you are moving... 

I have made the sizes equal, that will make it easy to move around things..

**Comment by chloedenavit** [comment]
ok thanks. We will add this info to the manual.
