### ISSUE TITLE
Have users at country level see only their own country when entering data in the Inventory

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#102]
Hi Abyot,
as you know, in the Survey/Dashboard tool we made the pilot countries see only their own data entry page (e.g. Guatemala can only see Guatemala in the tree menu on the left and cannot enter data for other countries).

- [ ] Can we do the same for the Inventory? 
So that when users from Chad sign-in with Chad's credentials, the "Country" field will be automatically populated with Chad. 

Please let me know if this is possible.
thanks,
Alisia

**Comment by abyot** [comment]
sure, that is possible. just create user(s) corresponding to each country like the way you did for the dashboard.
