### ISSUE TITLE
delete metadata that is not assigned to a dataset

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#104]
- I will send you the latest list of questions so that you can clear the ones that are no longer needed.
- You will delete the metadata that we are not using.
- I will wait to review the category options until Abyot has cleared the data elements.

**Comment by chloedenavit** [comment]
Hi @abyot - just a reminder about this. Is this still something possible for you to do?

**Comment by chloedenavit** [comment]
Hi @abyot,
We've received the translated version of the questions for the Dashboard so I am starting to input the translations. I would really help me if you could generate and send me a list of the metadata that has not been assigned to any data set, so that I can delete it, and not spend time looking for a translation or checking if I need to translate it.
Thank you!
Chloe

**Comment by abyot** [comment]
You can use these two (technically they are the same). They list data elements, categories and category options.

http://109.237.25.74:9091/inventory/api/dataSets/cbuoJvckm7A.json?fields=name,dataSetElements[dataElement[name,shortName,categoryCombo[categories[name,categoryOptions[name]]]]]


http://109.237.25.74:9091/inventory/api/dataElementGroupSets.json?paging=false&fields=name,dataElementGroups[name,dataElements[name,categoryCombo[name,categories[name,categoryOptions[name]]]]]

**Comment by abyot** [comment]
It is now more or less clean and the max I could go. There are I think 2 or 3 places where I am not able to delete.

The thing is that there are some dimensions (not questions) which were linked to old questions but also to new ones... the linkage between these two made deleting such dimensions problematic.
