### ISSUE TITLE
Report names

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#106]
I will send abyot a list of new names for Special Reports.

I will send you a mock-up of the new three tabs and names and contents.

**Comment by chloedenavit** [comment]
hi @abyot,

Here are the new names for Special Reports:

- Number of agencies = Number of agencies by geographic area
- Agencies per region = Agency presence by geographic area
- CNAS = Alignment to Core Nutrition Actions
- Aligned Investments = Alignment and investment size

Could you also re-order the reports following the order listed here?

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
great, thanks!
