### ISSUE TITLE
Save button and locking data

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#107]
When the user is done entering data, they will go to Report tab and click on "Send notification of completeness" which will send a message to the dashboard of the superuser. (name of button to be confirmed).

When entering action instance data, users will only click Save, there will be no completeness button on each action.

**Comment by chloedenavit** [comment]
Hi @abyot, I have made mock-ups for each of the three tabs we discussed, uploaded in our Drive:

https://drive.google.com/file/d/0B2yiXieaqNPmRDg3R21xYUtYM3c/view?usp=sharing

**Comment by abyot** [comment]
Hi @chloedenavit,

Sorry if we have discussed this ...

We have now kind of removed the completeness functionality, that is ok... but how about locking? I mean do you want editing to be disabled once users have sent data is complete notification message? 

Also, how do we handle additional data entry after notification message is sent?

**Comment by chloedenavit** [comment]
@abyot will try to create a special authority so that after clicking the button, the data does lock, but the admin account can still unlock it upon special request (through email).

**Comment by abyot** [comment]
Fixed.To unlock completed data, users needs "Delete Data Set Completeness Registration" authority.
