### ISSUE TITLE
new question with numeric skip value

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#109]
Hi @abyot ,
 Is it possible to add a skip value for sub-questions of 5.5.2 and 5.5.3 so that they only show up when the user types a number greater than 0 in the main question? If they type 0, then the questions won't show up. Should I enter a specific "Skip value" ? I tried ">0" but it didn't work. 

In addition, I got this error when adding a new question to the data set:
![capture-data set issue](https://cloud.githubusercontent.com/assets/21313941/21427475/23e0104a-c855-11e6-8bc1-42a07d6a7fb7.JPG)

**Comment by abyot** [comment]
Hi @chloedenavit ,

The system is kind of designed that way... for questions of value type number - the skip value kicks off when parent value is other than number.

**Comment by chloedenavit** [comment]
OK, so which skip value should I enter so that the question appears only if a number greater than zero is entered?

**Comment by abyot** [comment]
You don't need to enter any value.

**Comment by chloedenavit** [comment]
OK, then do you know why the question I have added, that should come below 5.5.2, is not showing up when I enter a number? 
The question is "Please briefly describe the UN Network's involvement and activities this past year towards Question 5.5.2."

![image](https://cloud.githubusercontent.com/assets/21313941/21645350/029e3b22-d292-11e6-9fb9-7d43d403454d.png)

This is the skip logic I set up:

![image](https://cloud.githubusercontent.com/assets/21313941/21645410/287f812a-d292-11e6-88bf-dd0badaaa265.png)

**Comment by abyot** [comment]
seems you forgot to assign it to the dataset.
