### ISSUE TITLE
Definitions

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#11]
Hi @abyot 
We noticed that the definitions are now showing up above the questions instead of below them. Why is that ? We preferred when they were below. Could you please move it back to showing up before the questions? 
Thank you!

**Comment by abyot** [comment]
Yes, definitions were coming at bottom. However, in some cases there could situations were definitions come at the bottom of the table and they will be difficult to see - unless the user scrolls down.

I have moved them down.

**Comment by chloedenavit** [comment]
Okay, thanks a lot

**Comment by abyot** [comment]
Definitions are now displayed at bottom.

**Comment by chloedenavit** [comment]
Hi @abyot 
I added definitions to all of the "Level of support" questions and I was wondering if it is possible to seperate a definition into multiple paragraphs. You'll see that the three definitions are listed one after the other continuously, and I'd like them to be easy for a reader to see that there are three definitions. 
Any suggestions? If you teach me how to do it, I am happy to make the changes for every single Level of Support question so that you don't have to do it.

**Comment by abyot** [comment]
Hi @chloedenavit ,

No this is not possible. This is similar to the issue we had - underlining a specific text from a description. For descriptions, the metadata allows us to provide a simple text in just one box - formatting is not allowed :(

**Comment by chloedenavit** [comment]
Okay, thanks. In this case, we should put the definition for the 3 levels of support somewhere else so that they are easy for users to read and understand. Any suggestions?

**Comment by abyot** [comment]
Can we use the CAPS LOCK approach we had for the other issue?

If not, then I can hard code i.e. whenever the category name for the drop down is "Level of support", I can use whatever format and text you want. 

Two things to note: 
- Once decided on a text and format, there is no way to change it through metadata
- name to level of support has to always be "Level of support". It can be anything, but can not be changed later.

**Comment by chloedenavit** [comment]
I don't think the Caps Lock will be clean and clear to read. I think hard code would be better. However, please wait until our reviewers come back with comments (tomorrow) before doing this change because the whole "Level of support" aspect of the Dashboard is subject to discussions tomorrow. Thanks!

**Comment by abyot** [comment]
sure, let me know once you have reached a decision. Keep in mind the two restrictions :(

**Comment by chloedenavit** [comment]
Hi @abyot ,
Since the review processes are finished, I believe the definitions for Levels of Support are now confirmed and won't be changed. Could you therefore hard code this text so that the three levels are each in a new line, and also capitalize the words LIGHT SUPPORT, MODERATE SUPPORT and INTENSE SUPPORT.
Thanks!
