### ISSUE TITLE
Special report formatting

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#110]
hi @abyot,
Quick request: In the CNA report, I noticed that there is no padding between the agency names and the edges of the cells, so it is quite hard to distinguish between the agency names since they are all accronyms: 
![image](https://cloud.githubusercontent.com/assets/21313941/21430578/0f42ac1a-c864-11e6-9667-f5dcd15f6435.png)

Would it be possible to add some space before and after the agency name, so they are easier to tell where one stops and the next one starts? 

This much (or even a bit less) would be fine:
![image](https://cloud.githubusercontent.com/assets/21313941/21430634/42c18534-c864-11e6-82c7-8c5178bf4d59.png)

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
great, thanks.
