### ISSUE TITLE
Red Important message in Dashboard - formatting

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#111]
Hi @abyot,
I have received feedback that the message in the red box in the Dashboard system is _too_ noticeable and is distracting from the rest of the information. Users see that message before they see the Outcomes and Outputs. Could we make the following adjustments to reduce this problem? 

1. Decrease the size of the margins (Similar to the margins you gave to the Question Warning)
2. Remove the **bold**.
3. Change the red color to the one you used in the "Mark Report Not Complete" button, when the mouse is not hovering over it: See screenshot. This red is a bit less strong.
![image](https://cloud.githubusercontent.com/assets/21313941/21676061/8f98ce96-d334-11e6-8c5a-fb0f7b2979ca.png)

Thank you !

**Comment by chloedenavit** [comment]
Here is a mock-up I just made:
![red message mock up](https://cloud.githubusercontent.com/assets/21313941/21676839/bc1a16ca-d337-11e6-910f-1cd8496e9e3d.jpg)

**Comment by abyot** [comment]
ok, good. 

since you are very specific:

1. Can you send me the red color code you used or is it the same as the "Mark report not-complete" ? I just wanted to make sure it is as you wanted it.

2. Seems you have increased the curve radius (the edges of the box) - is that intentional? It looks different from the other edges. If intentional, then please send me the radius value you used.

**Comment by chloedenavit** [comment]
Thanks for the questions! 
1. It is the same color as the "Mark Report Not-complete" button.
2. That was not intentional. The edges you had before were fine.

**Comment by chloedenavit** [comment]
hi @abyot, 
do you think you will be able to work on this formatting issue today? I need to take screen shots for the manual and will need to replace them when this is edited.
Thanks!!

**Comment by abyot** [comment]
Yes, fixed.

**Comment by chloedenavit** [comment]
Thanks for changing the color. Could you also do the steps 1. and 2. ? 

"1. Decrease the size of the margins (Similar to the margins you gave to the Question Warning)
2. Remove the bold."

**Comment by abyot** [comment]
I feel we shouldn't be creating any more issues except for bug fixing.

**Comment by chloedenavit** [comment]
Sure, I agree. But these requests were already in this issue ?

**Comment by abyot** [comment]
ok, I can fix that. but for me this is like asking for new development.

**Comment by abyot** [comment]
Is this ok?

![image](https://cloud.githubusercontent.com/assets/4967749/21805675/c19398c2-d735-11e6-81d0-cef15ee52c39.png)

**Comment by chloedenavit** [comment]
yes, thanks.

**Comment by abyot** [comment]
Fixed.
