### ISSUE TITLE
colours

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#112]
hi @abyot,
Did Alisia ever provide you with a list of colors ranked in the order we want them to appear? I don't see any record of this... If not, I will do that now. 
Thanks!

**Comment by abyot** [comment]
no. I think in one of the issue or email, I have provided a list and the next step was to rank them...

**Comment by chloedenavit** [comment]
Yes... I tried to search for it in my email and in issues but I could not find it! Could you send it to me again? Really sorry.

**Comment by chloedenavit** [comment]
Hi @abyot,
Here is the list of colors:

#ffd700|#ff8c00|#8b2500|#cdcd00|#228b22|#458b00|#00b2ee|#104e8b|#191970|#ee3b3b|#458b74|#838b8b|#8a2be2|#cd5b45|#6495ed|#8b4500|#8b3a62|#607b8b|#00868b|#8b1a1a

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
Hi @abyot - Would it be very time consuming for you to replace one color from this list of colors that I sent you ? The two greens look very similar to one another so Nicolas has asked me to replace one of them... Could you remove #228b22 and replace it with #551a8b?

**Comment by abyot** [comment]
Fixed.
