### ISSUE TITLE
Scrolling issue is back

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#113]
Hi @abyot,
I'm unable to scroll down among the data visualiser dimensions. For example I cannot go down to Yes/No.

![image](https://cloud.githubusercontent.com/assets/21313941/21683662/9832aef2-d35a-11e6-9d87-e79601c2949d.png)

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
Sorry Abyot but this issue is happening again... Are there steps I can take myself if this happens again?

**Comment by abyot** [comment]
Sorry, it is my fault that I forgot to apply the patch. Most probably, the new color code is also not working. I will apply the patch and update the system

**Comment by chloedenavit** [comment]
You're right, the colors weren't working either but I didn't want to both you with that :)

Let me know when you've applied the patch so I can check and update some screen shots. Thanks!

**Comment by abyot** [comment]
Fixed.
