### ISSUE TITLE
Visualisation for Joint Programme question: Indicators needed

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#119]
Hi @abyot,

I am working on making graphs to display data from Outcome 5.3.1 - Joint Programmes.

I would like to make a chart that will contain the data aggregated across _one column_ (for example Thematic Areas) but including ALL Joint Programmes (Joint Programme 1 + Joint Programme 2 + Joint Programme 3, etc.). Right now I am only able to make a graph displaying data from ONE programme at a time because they are each a separate question.
![image](https://cloud.githubusercontent.com/assets/21313941/21719152/6c803d0c-d41c-11e6-9518-817002148824.png)

Could you make indicators that would include the list of data that was entered for all Joint Programmes, but in one specific column? 
See explanation in this mock-up:
![image](https://cloud.githubusercontent.com/assets/21313941/21719216/cadacca0-d41c-11e6-8d85-25ff3bfb5a32.png)

Thanks!

**Comment by chloedenavit** [comment]
hi @abyot, just checking in to find out if you think this will be feasible? Otherwise, I will try to find another way of analyzing the data.

**Comment by abyot** [comment]
not sure I get this question correct... I don't think you need an indicator here.

Have you tried to use  "Joint Programme Dimensions Group" ? Using "Joint Programme Dimensions" provides you non aggregated result for the selected dimensions. If you use the group one "Joint Programme Dimensions Group", it will provide you a semi-aggregated result as per the group dimension selected.

**Comment by chloedenavit** [comment]
yes, you're right! Thank you! I was not clear on what the difference was between those two dimensions and how they worked. Maybe they were created while you were working with Alisia. Anyway, thanks!
