### ISSUE TITLE
Organisation Unit Renaming

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#12]
Hi @abyot ,
I have a question about renaming the organisation unit in the green box at the top of the data entry screen. If we rename it to "SUN Country" for example, would it be possible to rename this throughout the entire system, so that a person using the reporting app can see that name as well. We are worried that people won't know what "organisation unit" means when using the system (for data entry and for creating graphs). 

If it's not possible to change it everywhere, then we should leave with this name in the green box. I will just create a definition and we can add an information icon to explain it to users.
Thanks!

**Comment by abyot** [comment]
No, we can't rename organisation unit in the entire system - as that will be a lot of work changing each and every pieces of the DHIS2. But I can rename in the dashboard app.

I think the best would be to train the users... at some point they are going to refer to DHIS2's user manual.

**Comment by chloedenavit** [comment]
I see. In this case I think it is best to the same we did for the SUNPMT, which was to have a definition pop up if someone hovers over that word in the green box.

**Comment by abyot** [comment]
yes, we can do that. Just send me a mock up, like Kris did, putting descriptions for those items in the screen that you would like to put clarifications...

**Comment by chloedenavit** [comment]
Actually I only need a clarification for Organisation Unit because the other things seem self- explanatory: "The organization unit refers to the SUN Country of focus. Using the menu on the left, select the SUN Country for which you would like to view or enter data."

Thank you!
