### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#120]
I noticed that three of the staff levels in question 5.4.2 are aligned to the left, while the rest are aligned to the right. 

![image](https://cloud.githubusercontent.com/assets/21313941/21719608/eab69be2-d41e-11e6-83d4-73f2a3356617.png)

Can you fix thix? Aligning to the right is good, the way the rest are now.

**Comment by abyot** [comment]
Actually all are right aligned. The issue with the texts you mentioned are because they have overflow. Since you wanted to make it really to the right, I have fixed it by setting text direction right-to-left for that specific area. Direction rtl should kind of be reserved for texts like arabic...
