### ISSUE TITLE
Language menu

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#121]
Hi Abyot,
On the home page, before logging in, the language menu lists a lot of languages. Can we remove them all and only keep English and French? 
Thanks!
Chloe

**Comment by abyot** [comment]
It is not that easy. This will affect lots of other modules of the system.

Also, in my view - the best would be to inform users so that they set proper language. What will happen if a country wants to use in a language other than French and English?

**Comment by chloedenavit** [comment]
OK, then you can leave it.
