### ISSUE TITLE
Bug: Translation

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#123]
When I clicked on French I did not see the metadata I had entered into French displayed.

**Comment by chloedenavit** [comment]
Hi @abyot, I have an update on this. 

I am now seeing the French metadata displayed for the questions, which is great. However, I don't see the definitions in French, even though I pasted definitions into all of the questions. 

![image](https://cloud.githubusercontent.com/assets/21313941/22024948/12193b1c-dccc-11e6-86e6-23790a6a68d2.png)

**Comment by abyot** [comment]
It is two types of translation - one if the UI itself, the other is the metadata ( or db).

To see the questions translated - it is important to set Database language to French.

![image](https://cloud.githubusercontent.com/assets/4967749/22028890/090bbb6e-dcd9-11e6-9721-dfdae77c8ffd.png)

This also requires a logout -> login and cache clearing.

**Comment by abyot** [comment]
@chloedenavit  Where did you paste the definitions?

The definitions are stored as the data element (question) description and I don't see French text in any of the questions description.

See here for convenience 

http://109.237.25.74:9091/inventory/api/dataElements.json?fields=displayName,description&paging=false

or here

![image](https://cloud.githubusercontent.com/assets/4967749/22029257/43255034-dcda-11e6-8e53-3782ee9a51cc.png)

**Comment by chloedenavit** [comment]
Yes, I pasted in the French translation of the definitions into the Description box of the data elements:

![image](https://cloud.githubusercontent.com/assets/21313941/22029572/3f8b2790-dcdb-11e6-9283-c4e4229a097d.png)

**Comment by abyot** [comment]
This should be ok now.

**Comment by chloedenavit** [comment]
yes, it is, thanks a lot.
