### ISSUE TITLE
Translation of terms done

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#125]
Hi @abyot,
I'm sending the list of the terms I have translated, for you to enter into the system.

data_entry=Saisie de données
org_unit=Unité d’organisation
org_unit_dashboard_info=L’unité d’organisation est le pays SUN concerné. Utilisez le menu situé sur la gauche pour sélectionner le pays SUN pour lequel vous souhaitez insérer ou visualiser des données.
please_select=[Sélectionner]
search=Rechercher
select_or_search=[Rechercher]
loading_tree=Menu en cours de chargement
loading_metadata=Métadonnées en cours de chargement
in_progress=En cours
error=Erreur
go=Go
yes=Oui
no=Non
add=Ajouter
save=Sauvegarder
description=Description
required=Requis
unable_to_fetch_data_from_server=Impossible de récupérer les données dans le serveur
are_you_sure_to_delete= Êtes-vous sûr de vouloir supprimer?
previous_periods=Périodes précédentes	
next_periods=Périodes suivantes
prev=Préc
next=Suiv
empty=[ Vide ]
survey=Questionnaire
year=Année
error=ERREUR
info=INFO
warning=Avertissement
no_data_exists= Aucune donnée existante
export_excel=Exporter en format Excel
export_pdf=Exporter en format PDF
comment=Commentaire
are_you_sure_to_mark_complete= Etes-vous certain d’avoir complété le questionnaire dans son intégralité ? 
are_you_sure_to_mark_not_complete=Etes-vous certain de vouloir reprendre la saisie de données ?
success=Effectué
back_to_data_entry=Retour à la saisie
mark_complete=Questionnaire complété
mark_complete_desc=En cliquant sur ce bouton, vous certifiez que la saisie de données est terminée pour le pays et l’année sélectionnés. Une notification sera automatiquement envoyée au Secrétariat. Vos données pourront être utilisées pour la création de rapports officiels, disponibles au niveau global.
mark_not_complete=Questionnaire non complété
mark_not_complete_desc=En cliquant sur ce bouton, votre questionnaire ne sera plus considéré comme complet. Les données saisies ne seront pas utilisées pour la création de rapports officiels au niveau global.
marked_complete=Questionnaire marqué complet
marked_not_complete=Questionnaire marqué incomplet
select_thematic_area=Veuillez sélectionner les domaines thématiques depuis la liste de gauche.
select_action_left=Veuillez sélectionner les actions depuis la liste de gauche.
please_select_left= Veuillez sélectionner depuis la liste de gauche.
required_fields_list=Veuillez répondre aux questions suivantes
outcome=Résultat
output=Produit
question=Question
show_definition_info=Cliquez sur les questions qui ont des icônes d’information pour visualiser leurs définitions. Toutes questions dans chaque résultat et produit doivent être complétées.
missing_definition=Il n’existe pas de définition pour cette question. view_data_as_table=Afficher données saisies
view_data_as_table_desc=Ce bouton permet de visualiser toutes les questions dans un tableau, ainsi que les données qui ont été saisies jusqu’à présent pour le pays et l’année sélectionnés.
important=Important
joint_program=Programme Commun des Nations Unies
chars_remaining=Caractères disponibles
un_ntk_sun_rs=Ressources du Réseau des Nations Unies
user_manual=Manuel d’utilisation pour l’outil de suivi du Réseau des NU
un_ntk_sun_tools_rs=Outils et ressources du Réseau des NU pour le SUN
un_ntk_sun_str=Stratégie du Réseau des NU pour le SUN (2016-2020)
mtd_nut_exp_tra=Méthodologie pour le suivi des investissements en nutrition
can_for_nut=Compendium des Actions de Nutrition	
report_completed_not_editable=Le questionnaire de ce pays a été complété et les données ne sont plus modifiables. Si vous souhaitez effectuer des modifications, veuillez cliquer sur Questionnaire non complété. 
url_desc=Télécharger la Méthodologie pour le suivi des investissements en nutrition

**Comment by abyot** [comment]
Applied to the system.

**Comment by chloedenavit** [comment]
Thanks! I see one that didn't work: view_data_as_tables :

![image](https://cloud.githubusercontent.com/assets/21313941/22024685/100adc64-dccb-11e6-8bd5-c3af3f1ac3d1.png)

**Comment by abyot** [comment]
that is because the French translation file was wrong... 

![image](https://cloud.githubusercontent.com/assets/4967749/22025091/aea8cb14-dccc-11e6-8b31-86f14b94ce27.png)

Each translation key needs to be on new line.

Would be nice if you could go through the actual source and make sure everything is in place. Here is the source

https://github.com/abyot/sun-inventory/blob/master/dhis-web/dhis-web-apps/src/main/webapp/dhis-web-sun-survey/i18n/i18n_app_fr.properties

Just click on the edit / Pen icon...

**Comment by chloedenavit** [comment]
Thanks for sending. The rest looks good!
