### ISSUE TITLE
question order

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#128]
hi @abyot,
I have added a new question inside 5.3.1 but I can't get it to be the last in the list, after the table. I put the order as "50" after trying "13" (what i think it should be) but it always stays above the table. Can you help? 

New question is:
If you have selected "Other" in any of the cells above, please name the agency, thematic area or partner:

![image](https://cloud.githubusercontent.com/assets/21313941/22067243/bda349d6-dd90-11e6-9d27-267d73573f0f.png)

**Comment by chloedenavit** [comment]
@abyot  any idea how to fix this one?

**Comment by abyot** [comment]
you know what I am thinking ... we are having kind of a "scope creep" , we keep pushing

the plan we had back then was to kind of threat that table somehow specially ... this means breaking the order logic we have. now suddenly we want to bring back the order logic... the next question then is going to be to create a question whose order is going lie somewhere in between the table ... I don't know what to do with that.

**Comment by abyot** [comment]
This is not possible, sorry.

If we have to have the order, then we need to drop the idea of maintaining the group table. We can respect order only if we treat each question independently.

May be you could say "in any of the cells **below**" instead of "in any of the cells **above**"

**Comment by chloedenavit** [comment]
OK, no problem. I will say "in the table below". Totally understand that this table was a special circumstance and won't work as the other questions do. Thanks!
