### ISSUE TITLE
bug: entering values in the staff and budget tables

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#129]
hi @abyot.
 A new bug has occured. When I enter a number in one cell of the tables in output 5.4, all of the other cells suddenly are filled with the same number. I have cleared my cache several times throughout today but it keeps happening. 

![image](https://cloud.githubusercontent.com/assets/21313941/22208351/dcb43560-e182-11e6-963b-dbcff781dd05.png)

**Comment by abyot** [comment]
ok, will take a look.

**Comment by abyot** [comment]
Fixed.
