### ISSUE TITLE
Translation not working well

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#130]
Hi @abyot,

I just logged on to an account which I have set to French, and some of the text is in French (the terms which you gave me codes for) but the metadata is all in English.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/21313941/22329631/6a22fe9a-e3c2-11e6-973f-c83f59bdf8b5.png)

 I double checked the Settings and they are all set to French. I tried to re-select the same language again and clear the cache but it did not change. 

User settings:

![image](https://cloud.githubusercontent.com/assets/21313941/22329657/95624f70-e3c2-11e6-94a1-db037e2b9f5f.png)

Maybe when you do the changes you mentioned about the scrolling and the colors, this will be fixed? What should a user do if this happens?

**Comment by abyot** [comment]
Hi @chloedenavit 

This is a correct as far as the system is designed. Whenever a metadata is changed - cache needs to be cleared so that a new version of the metadata is downloaded including a French version.

**Comment by chloedenavit** [comment]
Sorry if I was not clear, but actually when I tried to re-select the same language again and clear the cache, nothing changed. The metadata still is in English...

**Comment by abyot** [comment]
I can see it working fine here. Logged in with Admin, and I can see all in French as per the setting.

Normally it is unlikely for the same user to switch back and forth between different locales. If this is the case, then one needs to do the following:

- change locale - Interface and/or data base language
- log out
- clear cache
- login

**Comment by chloedenavit** [comment]
Hi Abyot,
I logged out and logged back in and that fixed the issue.

However I am having issues with translation of the desciptions in the metadata again. I am using the link provided by WFP IT (http://wfpromshap11.global.wfp.org:15880/dhis-web-sun-survey/index.html#/dataentry). I have been editing the translation of descriptions and after clearing my cache and logging in and out, they are not updating. Is it not possible for me to edit the translations of the descriptions? 

I thought that I would be able to edit the metadata at any time, so I left the checking of the french descriptions until today :( I am now reviewing them for errors and I can't correct the errors... What should I do?

**Comment by chloedenavit** [comment]
Oh perhaps you can't access that link because it's only accessible through the WFP network... Sorry. 

Anyway, let me know what I should do, thanks.

**Comment by abyot** [comment]
For me, it is a little early to move to the WFP server. I don't know things from your side on the timeline. Since we are still working on issues... I would say wait a little. Let's finish on the test server... when done you can ask the IT team to update with new dB and system.

**Comment by abyot** [comment]
Yes, you should be able to manage metadata anytime. 

Can you ask the IT team if they are using any caching system for example nginx?

**Comment by chloedenavit** [comment]
OK, I will ask them. 

The reason we have moved it to the WFP server is that we have planned to send the link out to all our users today or tomorrow, and definitely by Monday at the latest. It seemed to me that all our issues are closed now, but I was planning to edit metadata on the WFP server. I'll ask them about nginx.

**Comment by chloedenavit** [comment]
The IT colleague said:

"There are no caching systems in place for your application. If you have an example to show me, please send me the link"

**Comment by abyot** [comment]
I can't tell for sure what the issue is.

What happens if you apply the metadata change on the test system we have been using?

**Comment by chloedenavit** [comment]
It's working now! I have no idea what happened...
