### ISSUE TITLE
Inventory bug in action link

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#133]
Hi @abyot,
When I select the section FOOD, AG, DIETS, and the Thematic Area "Food Processing, Fortification and Storage", none of the types of support or actions are coming up in the drop-down lists. They are blank. Can you help?

Thanks,
Chloe

**Comment by abyot** [comment]
May be there is something wrong with the group and group set configuration.

What happens if you select something else?

**Comment by chloedenavit** [comment]
If I start by selecting the Action, I can select the ones in that Thematic Area. But all of the previous drop-downs load correctly, except the Thematic Area box, which remains blank. When I then try to select the correct Thematic Area, the boxes below go blank.

**Comment by abyot** [comment]
ok. Since it has been a while, I don't remember exactly. Will have to take a closer look. In the mean time, if you can - please use the other selections.

**Comment by chloedenavit** [comment]
Sure, no problem. I can check back with you mid-next week maybe. I will continue to enter codes for actions and sub-actions in the meantime. 

Something strange is that all the action have mis-matched "short names" and most actions don't have codes assigned, even though I remember adding them... I am not sure how that happened. Anyway, I will correct them. I can't really remember the status precisely either!

**Comment by chloedenavit** [comment]
Hi @abyot,
I have finally finished enterring the sub actions!

But I've found another problem with the drop-down lists - I am not able to select the "type of support" when I choose certain thematic areas:

![image](https://cloud.githubusercontent.com/assets/21313941/23506033/68c7583a-ff46-11e6-9247-86c45fc8aef6.png)

**Comment by abyot** [comment]
Some time back we have made a naming convention for organizing actions in terms of thematic area, support types and other sub-groupings. Our approach was to make three groups and place actions accordingly.

We have three groups: 
1. Thematic area: the naming convention here is "Name of thematic area"
2. Enabling environment: naming convention is "Name of thematic area - Enabling Environment"
3. Procurement, logistics & supply: "Name of thematic area - Procurement, logistics & supply"

This naming convention was not respected for the groupings you mentioned not working. See below, specifically on the exact matching of spellings:

![image](https://cloud.githubusercontent.com/assets/4967749/23823502/575ac864-0664-11e7-947e-b444b40b0e4f.png)

Same with Multi-sectoral Nutrition Governance. The thematic area was named as "Facilitation of Multi-sectoral Nutrition Governance" while the enabling environment was names "Multi-Sectoral Nutrition Governance - Enabling Environment"
