### ISSUE TITLE
Report of action codes

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#134]
Hi Abyot,
Would it be possible for you to generate a report showing the data elements that have a certain action code? I want to find out which data element has code AC19, AC20, and AC21.

I also would like to know if I can generate a report showing all data elements and their action codes, just so I can double check them? 

Thanks!

**Comment by abyot** [comment]
Hi,

Not sure I understood the question here. One thing I can say is we haven't considered codes in reporting. If that is the requirement, then we need to kind of articulate what exactly is needed and implement it.

If the question is to list data elements together with their codes, the following might help:

Listing all data elements together with their name (displayName) and code

http://109.237.25.74:9595/unnutritioninventory/api/dataElements.json?fields=displayName,code

This one returns with paging, i.e. 50 items at a time. If no paging is required (one needs to be careful in case there are lots of data elements)

http://109.237.25.74:9595/unnutritioninventory/api/dataElements.json?paging=false&fields=displayName,code

Also possible is to search for data elements based on their code value

http://109.237.25.74:9595/unnutritioninventory/api/dataElements.json?paging=false&fields=displayName,code&filter=code:eq:AC20

**Comment by chloedenavit** [comment]
Perfect, thanks. The first list is what I needed. Can I generate these myself or only you can do it?

**Comment by abyot** [comment]
The system supports restful api. Anyone with access to the system, knowledge of DHIS2 data model and rest api syntax can generate it.

**Comment by chloedenavit** [comment]
ok, thanks!
