### ISSUE TITLE
sub-action links

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#135]
Hi Abyot,

When I select the action below, the wrong sub-actions come up. I have checked the Action codes and they are correct. Can you help?

Selection:
![image](https://cloud.githubusercontent.com/assets/21313941/23506806/5de3b4d2-ff4a-11e6-9f5c-59bcca9cbc0d.png)

Data element code is correct:

![image](https://cloud.githubusercontent.com/assets/21313941/23506823/71aac776-ff4a-11e6-99c6-ee643d73c774.png)

Option Set code is correct:

![image](https://cloud.githubusercontent.com/assets/21313941/23506836/83f064c2-ff4a-11e6-879e-08d668973015.png)

But the sub-action that I had entered as an Option is different from the one that shows up:

![image](https://cloud.githubusercontent.com/assets/21313941/23506866/a0687298-ff4a-11e6-94b7-77e25df360e7.png)

**Comment by abyot** [comment]
This is wrong. Code needs to be assigned for the data set not data element - that is how the system was designed. See issue #69
