### ISSUE TITLE
Removing all data from sub-regions under Rwanda

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#136]
Hi @abyot,
As we decided to use the regions for the Inventory as "tags", we don't need the sub-regions under Rwanda to show up, and in fact I would prefer to remove them. I tried to do this in Maintenance but could not because there is some data in them. I believe we entered data before we decided to change our approach. 

Can you delete all data that is in the org units one level below national, for Rwanda? If this will be time- consuming for you, then I prefer to do it myself - Could you run a report to show me exactly in which Org Units and instances the data is located so that I can delete them quickly? 

Thanks a lot!

**Comment by abyot** [comment]
See if this helps http://109.237.25.74:9595/unnutritioninventory/dhis-web-pivot/?id=OLYbBGRv1bk

**Comment by chloedenavit** [comment]
Good idea! It does.

Thank you,
Chloé

**Comment by chloedenavit** [comment]
Hey abyot,
I removed all data, and generated the table you sent me after running analytics, and it confirmed there was no data, but when I try to delete the sub-regions, it still says there is a Data Value preventing its deletion:

![image](https://cloud.githubusercontent.com/assets/21313941/23850104/58f864e4-07de-11e7-9b5e-e3c653d5c9fc.png)

**Comment by abyot** [comment]
ok, I will check.
