### ISSUE TITLE
Deleting Rwanda's org units

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#137]
Hi Abyot,
I'd like to delete the sub-national org units because we are only going to be entering inventory data at the country level (and using the labels / tags to identify regions, if you remember). 
I couldn't delete the sub-national org units under Rwanda because there is data attached to some of them, but I can't find them.
Could you generate a report of all the data that was entered in Rwanda sub-national units? I'd like to delete them all.

Thanks!
Chloe

**Comment by abyot** [comment]
This is the data registered under Rwanda subunits.

![image](https://cloud.githubusercontent.com/assets/4967749/25592421/07e2a3ce-2eb9-11e7-8ae8-2606311d3458.png)

**Comment by chloedenavit** [comment]
Thanks, this SQL report is fine! Could you generate one that also tells me the year and agency name? I went into that first action (crops/horticulture - assessment and info) and I don't see data for 2016 in any of the agencies... 
Thanks

**Comment by chloedenavit** [comment]
@abyot could you please delete all the data. 

When you have done that, could you delete the sub-units under Rwanda?

**Comment by chloedenavit** [comment]
Hi @abyot. Could you please clear all the data in the Inventory, so that I can delete Rwanda's sub-regional units, and also so I can do a new test data entry process, to test the system?

**Comment by abyot** [comment]
Data is now cleared. I have also removed all sub-units under a country.
