### ISSUE TITLE
"Sub-actions"

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#138]
When entering the sub-actions, I found that some of them are too long to fit the whole name into the text box (some of the sub-actions even have a list inside). I have decided that I will just cut them short when the characters run out, and put "..." at the end. However, I'd like to note somewhere that the full names are in the CAN document so that people aren't confused what happened to the end of the sentence.

I am wondering if you can change the text that says "Sub-actions" in bold, and add [Refer to CAN for full name of sub-actions].

See mock-up:

![image](https://cloud.githubusercontent.com/assets/21313941/24995584/98199620-202f-11e7-88fc-ebe1a16e3139.png)

**Comment by abyot** [comment]
Don't you think having "[Refer to CAN for full name of sub-actions]" all the time will confuse - even if we have the full name displayed?

**Comment by chloedenavit** [comment]
Good point, I think you're right. For now let's not put it. When I add the French translations we may need to say something, but we'll see.
