### ISSUE TITLE
One sub-action not showing up

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#139]
Hi @abyot,
I've edited the action and sub-action codes and am now reviewing all links to make sure they're correct. I did find one issue that I cannot resolve: The sub-action for "Coordination - Food Processing, Fortification and Storage" does not show up when I select it. I've checked the data set, data element, and option set but cannot find the reason. Could you help me?

Here is a screen shot:
![image](https://cloud.githubusercontent.com/assets/21313941/25127806/94ae82fa-2437-11e7-97f2-7e61c1f0b77b.png)

**Comment by chloedenavit** [comment]
Hey @abyot, 

The thematic area Micronutrient Supplementation is not in the drop-down list at all. Could you find out why?

Here is a list of other sub-actions that are not showing up even after I've tried checking their names and codes:
1. Under the thematic area Nutrition Interventions Delivered through Reproductive and Paediatric Health Services:
- Assessment and information
- Policy Coherence
- Legislation, etc
- Fiscal policy
- Planning etc.

3. Under the thematic area Nutrition-related Disease Prevention and Management:
- Nutritional care and support in HIV prevention and management

4. Under Water, Sanitation and Hygiene for Good Nutrition
- Water quantity and quality to support good nutrition 

5. Under social insurance:
- Insurance

6. Under social protection:
- Planning
- Coordination
- Infrastructure

I found other issues that I was able to fix, but not these ones. Thanks for your help!

**Comment by abyot** [comment]
The thematic area is appearing now... it was a metadata issue. It is the same for the sub-actions - the code for most of the data sets is not matching that of corresponding data element and option set. For example

![image](https://cloud.githubusercontent.com/assets/4967749/25591153/c02baaee-2eb3-11e7-8bc6-effbc58217e1.png)

vs 

![image](https://cloud.githubusercontent.com/assets/4967749/25591179/d55254e0-2eb3-11e7-9f69-cb25313356fa.png)
