### ISSUE TITLE
3.2.2. To be modified

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#14]
Hi Abyot,

In output 3.2.2, the questions should be the following:

Main question in bold: leave as it is now. If Yes, the following should appear:
Has the UN Network provided support to establish COI guidelines and/or policies? Yes/No
(If Yes:) Please rate the level of support provided by the UN Network to establish COI guidelines and/or policies: Light/Moderate/Intense
Has the UN Network provided support to mitigate COI issues and/or facilitate COI dialogue among stakeholders? Yes/No
(If Yes:) Please rate the level of support provided by the UN Network to mitigate COI issues and/or facilitate COI dialogue among stakeholders: Light/Moderate/Intense
Has the UN Network provided support to address other COI issues? Yes/No
(If Yes:) Please rate the level of support provided by the UN Network to mitigate COI issues and/or facilitate COI dialogue among stakeholders: Light/Moderate/Intense

**Comment by abyot** [comment]
This is fixed.
