### ISSUE TITLE
Unable to delete org units

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#140]
Hi @abyot,
I'm trying to delete 2 org units from the Dashboard because they are Test 1 and Test 2, but it says I cannot because they are associated with a "Data Value". However I went through and deleted all data associated with them so I'm not sure what's happening. Could you help? 

Thanks!
Chloe

**Comment by abyot** [comment]
Hi @chloedenavit 

That is probably because we have changed the metadata... because of the changes the data entry app will not pick the values since its starting point is the metadata. will try to find a way to clean data values and remove the units.

**Comment by abyot** [comment]
Hi,

Ask Giorgio to give you the following sql's ouput

select 
dv.value as value, 
de.name as dataElementName,
ou.name as orgUnitName,
dv.storedBy as storedBy, 
dv.created as created, 
dv.lastUpdated as lastUpdated
from datavalue dv 
inner join dataelement de on dv.dataelementid=de.dataelementid
inner join organisationunit ou on dv.sourceid=ou.organisationunitid 
where sourceid in (select organisationunitid from organisationunit where uid in ('IwLZPCv9SYd','OvKCFlRajn8'));

You can then go through it and decide whether to delete or not.
