### ISSUE TITLE
Changing name and definition of "procurement, logistics and supply"

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#141]
Hi @abyot,
I need to change the name of the type of support "Procurement, logistics and supply" and replace it with "Interventions". Could you do that? 
If you need me to do some manual meta-data modifications, let me know and I'll be happy to.

I also need to change the definition that pops up when hovering over the information icon next to Type of Support.  Please replace with:
UN support is categorized under one of two Types of Support: 1) Interventions and 2) Enabling Environment Actions. Whereas interventions are primarily provided to beneficiaries often as a ‘direct service’, enabling environment actions contribute to fostering an enabling environment for good nutrition.

Thanks,
Chloe

**Comment by abyot** [comment]
Hi @chloedenavit ,

The popup message is changed ... as to the renaming of type of support you can do it by editing data element group.

**Comment by chloedenavit** [comment]
Sorry but the pop-up hasn't changed, after I cleared my cache several times and used the browser cache cleaner app too. Could you double check?

**Comment by abyot** [comment]
Fixed @ http://109.237.25.74:9595/unnutritioninventory/dhis-web-action-inventory/index.html
