### ISSUE TITLE
"view only" users not able to open charts

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#142]
Hey Abyot,
I created a user with only "view only" abilities, and when I am in the Pivot Table App they can open Favorite Pivot Tables, but when I'm in the Data Visualizer App, they cannot open Favorite Charts. However, if I go to the Dashboard and Explore a chart in there, it does open. 

Do you know why that might be? 

Here's the error I receive:

![image](https://cloud.githubusercontent.com/assets/21313941/25742777/583cd6ac-3191-11e7-9e07-101821760e7a.png)

**Comment by abyot** [comment]
Hi Chloe,

The error says user HQ is not allowed to view org unit k545A4wRKG9 - which is Sun Countries. Can you make sure this user has access to view data ouput from this orgunit?

**Comment by chloedenavit** [comment]
Perfect, fixed it. Thank you
