### ISSUE TITLE
Data set 

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#147]
Hey Abyot,
If I remember correctly, in the Dashboard/Portal application, when creating a new Data Element, I had to add it to the "Dataset". But now, when I go into Maintenance > Dataset, the "selected" section is blank. This is the case both on the WFP version and on the demo. 

Is this an issue? 

I recently added some data elements / questions (WFP version) and they're not coming up. Is this the reason? 

![image](https://user-images.githubusercontent.com/21313941/29828810-1548176e-8cde-11e7-8664-909ac4736747.png)

**Comment by chloedenavit** [comment]
When I try to save new data elements to the data set, here is the Console information:

![image](https://user-images.githubusercontent.com/21313941/29859988-c6082aa4-8d64-11e7-8b8d-3b9d5e9a133a.png)

**Comment by abyot** [comment]
Fixed and demo is updated @ http://109.237.25.74:9091/inventory/
