### ISSUE TITLE
Public dashboard

### ISSUE THREAD

**Issue by abyot** [abyot/sun-inventory#15]
A very limited and read-only public dashboard is now available in the system.

If the intention is to provide more interaction with the general public - say for example allowing to pull different data, pivoting and rearrangements - I suggest to provide login access with limited authority.

**Comment by chloedenavit** [comment]
Thanks @abyot, this looks good! The read-only version is all they will need. 

I am a bit confused how the public will access it - is there a specific link to get there? I opened it myself but now I can't find a link...

**Comment by abyot** [comment]
It is the same link. If you logout - it will take you to the dashboard.

 We can control which visualizations to be available for public
