### ISSUE TITLE
Typing in the search bar doesn't reduce the drop down menu

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#150]
Hey Abyot,
During my meeting today showing the Inventory tool, I noticed that when I type a word into a drop-down list, the words with those characters become bold, but the list doesn't reduce in size. Does this mean it's not really a search feature, or the search feature is not activated? Would this be something you can add, or is it very complicated? 
If yes, how many days would it take you? 
Thanks!
Chloe

**Comment by abyot** [comment]
Hi Chloe,

Which drop down list did this happen? Do you have a screenshot?

**Comment by chloedenavit** [comment]
All of them do this. Here are two examples:

![image](https://user-images.githubusercontent.com/21313941/31238464-5aac25f0-a9fa-11e7-8bbb-9982bd1caa50.png)
![image](https://user-images.githubusercontent.com/21313941/31238503-72c61d80-a9fa-11e7-8fe0-251455ce244f.png)

**Comment by abyot** [comment]
Hmm... interesting. 

What happens if you try to search on any of the drop downs from the green area?

**Comment by chloedenavit** [comment]
It **does** work in the green (and blue) areas.

**Comment by abyot** [comment]
ya, that is what I expected. We are using the same logic/code for both... I think this happened because we introduced another filter (filtering options as per organisation units). 

Seems the two filters (one when typing and the other as per assigned organisation) are not syncing well. I will look into it.

**Comment by abyot** [comment]
Ok, this is fixed now and demo server is also updated.
