### ISSUE TITLE
reminder 

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#16]
Hi Abyot,

I know we have already talked about this, however these two things are very urgent.
- [x] could you please create a user profile (with level of access/permission different from ours of course) we can access with, so that I will be able to see what users are really going to see and what they will be really able to do/not do.
  I am asking this because I am creating a short manual for our first users and I need to know what they really need to be instructed on. I want to avoid writing a chapter on how to do or use something that they will not be able to play with or see.
  We can then use those level of access/permission for creating other users profile ourselves.
- [ ] Can you also create graphs for each answer inserted in the survey? Both at aggregated level and country level. It would be also good if on top of each graphs there was the correspondent question (**with its full text**) with its numeration (2.1.3, 5.4 and so on). This way we can easily understand what that graph is referring to. At the moment it's a bit confusing.

I know you suggested to talk about those issues during our call, but the manual I am preparing need to be ready by Friday, therefore I need to be able to access with the user profile and see all the graphs they will be able to see before that date.

There are many other things I need to ask you during our call but please **take the points above as priorities.** 

thanks!
Alisia

**Comment by abyot** [comment]
Hi @Alisia1 

Re: user creation

I have now created two users - just for sample. As I said, this is something for you to decide as it depends on what exactly you wanted to provide access or not.

username:  dataentry

This user can access the following

![image](https://cloud.githubusercontent.com/assets/4967749/19517386/394a3626-9601-11e6-8491-d4b08294739b.png)

As you can see, in addition to data entry there are also other apps this user can access. For me it makes sense for a user to visualize a data that he/she has entered. Do you want this or just data entry?

It is possible to restrict which countries a user can access. User **dataentry** can enter data for all countries. There is another user **dataentry_test**, this user can entry only to Test countries.

Also created is user **dataview**. Below is what this user can see

![image](https://cloud.githubusercontent.com/assets/4967749/19517600/7f34d10e-9602-11e6-8317-60af5b7d8763.png)



Re: generating outputs

Honestly, I don't have the time to "create graphs for each answer inserted in the survey". I have shown how outputs can be generated. I can also show again through Skype.

... anyways I can try to create some graphs in the evening, but definitely not for each question.

**Comment by Alisia1** [comment]
Thanks Abyot for creating the users profiles.

About the dataview one, maybe it would be good if they could only see the dashboard and play with the remove/resize/explore/share interpretation buttons, and not with the add/manage/share buttons which I thought were only for the admin users? please correct me if I am wrong.
Or, in the public version, can we add the possibility of exporting the graphs in pdf and excel?

About the graphs, entering as dataview user, I am trying to see how the Pivot Table app and the Report app work. I see that in some cases, even if I select the correct data elements, and periods and orgunits data, and click update, the report or the pivot table doesn't show.
Can you please confirm that the system has been set to be able to create all types of reports/pivot/dashboard using the data inserted in the survey already? If so, it means that I am doing something wrong.
I am trying to learn how to use these apps by reading the DHIS2 end-user manual in order to explain it to our users, but sometimes it doesn't work.

Thanks!

**Comment by abyot** [comment]
It is not possible to control specifically the add /manage/share buttons. These buttons are tied to the dashboard. i.e. they can only manage, share or add from their context or those they have access to. They won't be sharing anything they do not have access.

Re: export to pdf/excel in public versions:

This is not possible at the moment.

Re: not able to generate data using dataview

I can generate from here... Can you tell me the steps you are taking so that I can try to reproduce?

Re: report module:

For your data and use case, the only thing critical right now is the analytics section. You could use the approval if you wanted to have approval functionality. The rest, you don't need to use it. 

If you wanted to see country report, the one just introduced in the data entry module is the best to use. If time allows, I could extend this so that it allows generating aggregate report.

**Comment by Alisia1** [comment]
Hi Abyot,
ok, so I guess we will concentrate only on the "Data Visualizer" app, which is the one the dataentry users are going to see when clicking on "explore" in the bar above the dashboards.
You are right, the other app like Pivot and Report are not necessary at this stage.
Here the things I need some help with.

1. If I select the first graph on the left, the one corresponding to question 5.4.3, and I click on explore, I am redirected to the data visualizer app.
First, **I've noticed than the title of the graph here says "SUN Countries" and does not report the full text of the question like the same graphs does in the dashboard app. Same for the other graphs already displayed.**
- [ ] Can you please update them?

2. Once I am in the data visualizer app, let's say I want to change the graph, and see others corresponding to other questions and answers. So I go to Data --> Data Elements and select Output 1.1.1 and move it in the"Selected" column by clicking on it and then on the arrow in the "Available" column. Now the Output is in the right column.

3. Now I select the period (last 12 months) and the OrgUnit (Cambodia). **The problem is here is that I can't scroll down the countries list, it stops at Kenya.**

- [ ] Can you please fix this?

4. When I click on update, the image says "no data display" (image attached). Am I missing something? Being a yes/no question, I was looking for the yes/no option in the left column, where all the other sets of answers are displayed (below Organisation Unit) but I couldn't find it. The last option available is "UN Network supported categories" but you can't read it really well.

- [ ] Can you please fix this?

Do we have to select a type of answer for each output in order to see the graph?

About the same graphs, scrolling on the graph, you can see the values inserted for each staff level (IFAD --> UNV:101, IFAD --> UNV:60) but you can't see in which countries those people are based (e.g. which countries have inserted those data). 

- [ ] Is it possible to add that value?

- [ ] I also see data from the inventory in the data visualizer app, can we delete them?



thanks!

**Comment by abyot** [comment]
Hi @Alisia1 @chloedenavit 

Do you still think this is a valid issue?

**Comment by Alisia1** [comment]
we can close it!
