### ISSUE TITLE
Dataentry users: errors to fix

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#17]
Hi Abyot,

I used the data entry user yesterday and I noticed that data entered are not saved automatically as it should be, the box turns red and not green.

- [x] Can you please fix this?

We would like the dataentry user to look exactly like it will for our users.

Thanks!

Alisia

**Comment by abyot** [comment]
Hi @Alisia1 

Sorry, my fault. This is fixed now.
