### ISSUE TITLE
#17

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#18]
Hi Abyot,

as discussed on Friday, I will create a separate issue for every thing that needs to be fixed.
Here we start:

- [ ]  can you please leave the search box just above the Organisation Units tree open? (now it's not easy to understand that you have to click on the green magnifying glass to search for your country).
Actually I've tried to click on it but it doesn't open! What happened?

Thanks!

**Comment by abyot** [comment]
This is fixed. Try to refresh or clear your browser cache.
