### ISSUE TITLE
#18 Red instruction box

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#19]
The red instruction box on top of the different Outputs doesn't stand out. I mean, the color does but not the text. 

- [x] Can you please add the word IMPORTANT in capital letters at the beginning of the sentence?
Like "IMPORTANT! Click on questions with an information icon to view their definition. All questions in every Outcome must be answered before submitting the report."

Maybe IMPORTANT could be bigger than the other words?

Thanks!

**Comment by abyot** [comment]
This is fixed.
