### ISSUE TITLE
Dashboard call notes from 26 Sept 2016

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#2]
We would like Abyot to change the following things in the Inventory tool:
- [x] Create another "survey" that includes only Outputs 5.3 and 5.4, which will prompt a new drop-down box in the green area, where the user can select their UN agency. The answers to these questions will then be tagged to those agencies in the database.
- [x] Required questions: Every top layer question must be answered by Yes or No before a user can "Save as Complete". In addition, if the user selects Yes to one of these, then they must answer every question that will appear below it. 
- [x] When a user tries to click complete if a question has not been answered, would it be possible to identify exactly which ones have not been answered? For example: "Please select an answer for each question listed under **Output 4.5, Output 5.2** and **Output 5.4**. If this output is not applicable in the year being reported, please select 'No' for all questions listed. "

_In addition, here are some more requests since I reviewed the tool today:_
- [x] Could you please change the name of the App from "SUN survey" to "UN Network for SUN Annual Reporting Exercise"
- [x] Could you add a line or divider between each of the "top level" questions (the first ones that always appear), so that when a user has selected Yes and the questions below pop up, they can still easily see where this set of questions ends and where the next "top level" question is. 
- [x] Some questions should only appear when the answer selected is "No". For example, there are some in 5.1  and 5.2. However, I think it is better if we wait until we have the new version of the questions before modifying these things, because it may not be relevant anymore.

**Comment by abyot** [comment]
Hi @chloedenavit 

I have tried to do some remodeling so that we avoid creating separate surveys for 5.3 and 5.4. Now all in one survey. See here for more details http://109.237.25.74:9091/inventory/

Especially, I want you to briefly go through outputs 1.2, 2.2, 5.1, 5.3 and 5.4.

For now, I have turned off the skip logic, and focused on the layout of the questions. 

Another point,

I instead went for using color to differentiate the main questions than drawing a divider line. We already have too many lines :( ... but of course the decision is yours :)

Marking some questions as mandatory is coming together with the skip logic.

**Comment by chloedenavit** [comment]
Hi @abyot,
Thanks a lot!  I think the colours work well to distinguish the main questions.

Output 1.2: The last two questions have to be reversed so that the level of support question comes last. In addition, should there be a text box asking them to describe the activities ? 
Output 2.2: The last question seems to be a repetition of one that was already included a few questions higher up.
Output 5.1, 5.3 and 5.4: When I click on these they are empty, even after I cleared my cache.


_In addition, here are some other requests:_

- [ ] Thanks for changing the name of the App. I noticed that the name is cut off because it is too long (it stops at Annual). Therefore, could you rename it UN Network for SUN Dashboard ? 

- [ ] On the tree to the left of the screen, is it possible to replace "SUN Global" with "SUN Countries" ?

- [ ] When I click on an Outcome Tab, before selecting an Output, I see that it says "Please select from the left". That is great, but could you add "Please select an output from the left" ?

**Comment by abyot** [comment]
@chloedenavit 

Sure, will change the app name.

Seems the cache clearing didn't help. Can you try one more time? If in Chrome, ctrl + h and clear everything :(

**Comment by chloedenavit** [comment]
@abyot 
I tried again but it still doesn't seem to work. I know that I cleared the cache properly today because the other questions changed when I did it (turned blue, etc) but not those three outputs.

**Comment by abyot** [comment]
@chloedenavit 
sorry, my fault. I used a wrong db. Now fixed. Try, after clearing your cache.

When clicking an Outcome Tab, the first Output should be selected by default - meaning label "Please select from the left" should never show up.

**Comment by chloedenavit** [comment]
@abyot OK, it works now !

Output 5.1: 
- This question should allow multiple entries (not just one answer): _Which UN Network agency serves as the lead Chair?_
(Sometimes two or more agencies will co-lead the network).
- This question (_Please briefly describe the main reason(s) the UN Network has not developed an annual work plan_) should come right after the Main Question (_Has an annual UN Network work plan been developed?_) 
- How often has the Chair convened UN Network meetings with technical focal points this year? Could you please move the "Never" to be the first in the list? And the question below it should only appear if "Never" has been selected. 

Output 5.3: The second question should only appear if the first question is answered with a zero.

Output 5.4: 
- The third question should only appear if the first question is answered with a zero.
- Could we merge the first and second table by adding a third column to the right end of the first table with the title "If no UN staff dedicated to nutrition within the UN Network, please provide an explanation below".
-The third and fourth tables will need to be re-worked but I want to wait for the next version because I believe we will need to add additional columns. 

In addition, some questions should only appear if the main question answered says "No". I want to go through all the questions and identify these ones for you, but I would prefer to wait until I have the final set. I have asked my colleague again for the updated version and she said she would send me one by the end of today.

**Comment by abyot** [comment]
Yes, the skip logic thing  - what is displayed after what and when - is coming. I turned it off for now... so that you are able to see all questions and their layout.

Regarding, the merging of tables - no that is not possible. If we want to merge, then we need to rework the questions.

**Comment by abyot** [comment]
@chloedenavit 
Are you sure "Which UN Network agency serves as the lead Chair?" should accept multiple values?

**Comment by chloedenavit** [comment]
Merging of tables: OK, let's see how the final question is posed and think about a solution at that stage.

Lead Chair question: Yes, because in many countries the chair position is shared between two agencies who rotate (or potentially more than 2).

**Comment by abyot** [comment]
good, we wait and see on the merging. I have now made "Which UN Network agency serves as the lead Chair?" as multi-select.

**Comment by chloedenavit** [comment]
HI @abyot,
I just uploaded the new version of the questions for the Dashboard into our shared Google Drive (in Word and PDF, as well as a PPT version of the visualisations).

Output 5.4 still has the same table so we can go ahead and work on these:  
- [ ] The question in blue is above the right-hand column, which looks a bit odd. Could you move it to be above the left column, so that it is aligned to the other blue questions? 

- [ ] Staff Category and Staff Level: Instead of asking for categories first and then levels, I would like to merge these two to say "Staff category and level". Then, could you make the text box into a multiple choice drop-down (as with the UN agency names) ? I will provide you with a final list of potential options at a later date (I need to check across agencies so it will take some time) but, for now, you can put the following list in a drop-down: NOA, NOB, NOC, JPO, Consultant, P1, P2, P3, P4, P5, D1, D2. 

- [ ] There are actually 2 questions that have very similar wording, but both will need a table like the one above. You may notice that of them says "staff dedicated to nutrition" and one says " staff contributing to nutrition". Please be sure to include both of them. would it be possible to underline the parts of the questions that I just put in quotation marks so that users quickly see the difference?

- [ ] All of the questions in this survey have long definitions. How do you think we could include these in the tool? I am not sure that a "hint" icon or a pop-up are the best options because the definitions are so long and the users may need to refer to it multiple times while they are enterring data. Do you have any suggestions? Maybe we could add a small "Definition" button with an arrow next to every question and by clicking on it, a new box appears below the question, with the definition in it, which can be opened and closed. It would be important that they can still enter data while reading the definition. Does this make sense? If it's confusing I can try to find an example of what I mean...

Thanks for the work you've already done! Our Global Coordinator saw the progress so far and was very impressed. Good work!

**Comment by abyot** [comment]
Hi @chloedenavit 

I have tried to fix the skip logic and validation. On the validation, all questions that are displayed are marked as required - see a red asterisk at the end of each question. This tells users, it is mandatory to answer such questions.

When clicking complete, the system goes through the entire list of questions and validates if all marked required are answered. If not, it will block completion and instead throws a notification dialog ... like the one shown below ... I will fix the rowspan of the output column...

![image](https://cloud.githubusercontent.com/assets/4967749/18984686/4c148d54-86f4-11e6-8e46-a66dae0238fd.png)

As to the definition,

See a sample one below:

**Comment by chloedenavit** [comment]
The definition looks like great like this, thanks. However, I am not convince that it will be nature for people to click on the question itself... I think we should add either a little arrow to click on, or maybe a line of instructions at the top to inform the user of this option ("Click on the question to view definition").

Yes, I can enter all the definitions. However I have to work on some other things this morning so I will not have time to do this until the afternoon. Is that okay?

**Comment by abyot** [comment]
Regarding Staff Category and Staff Level, seems you are proposing a big change than we have currently. It is easy, if we avoid collecting that by agency. But if we still want to collect by agency, it is not possible with the current approach. We have to create a different survey and make agency as part of the green row combination.

**Comment by abyot** [comment]
Thanks. sure, you can enter the definitions whenever you have the time. 

I would go for putting a line of instruction at the top... 

If we go with icon/button ... users will still wonder what icon/button is going to do. what will happen is - users move cursor to the icon, get what it a sense of what it will be doing something like "click for more details", on click we display the definition. The hide the definition, they will still have to move to the icon....

also, it is easier to click on a long line of text then a small icon...

**Comment by chloedenavit** [comment]
We do still want to collect by agency, and I don't think your proposed table has to change at all, the only difference I am proposing is that for every agency, we only ask 1) "staff number" and 2) "staff category and level". Basically, I am proposing to delete one of the 3 questions and combine the second two so that the answer options include the category and level. The options will be P1, P2, P3, P4, P5, etc. This is the category (P) and the level (1). We should not ask for them seperately because we will not need to analyze them seperately. We will count, per agency, the number of P1, number of P2, etc.
Does that make more sense?

The line of text for the instructions sounds good to me!

**Comment by chloedenavit** [comment]
Hi @abyot,

I have entered the definitions for the questions. The new version has combined a few questions in order to reduce the number of questions. I tried to delete the extra questions but could not because they are linked to other elements. Now that I think about it, could we instead "hide" some of the questions that are no longer needed, just in case the questionnaire changes back to the original, so we don't have to type them again? If it's not possible, could you delete the extra questions (following the newest version of the questionnaire), or explain to me how I can do it? 

Question 2.4: There is now a table in the questionnaire, asking for the level of support disaggregated by activity. I know that this type of table won't be possible, so we'll need to find another solution. Could we perhaps create a question for each Activity in the table, and then ask for the "Level of support" for each one. Each question can be as follows: 
- "Has the UN Network provided support to estimate the social and economic impact of malnutrition and/or develop investment cases?"
- "Has the UN Network provided support to organize government-led investment round-table discussions?"
- "Has the UN Network provided support to navigate the nutrition-funding landscape?" 

After the log-in screen, could we have a text that says "Please select a SUN country from the menu on the left."

**Comment by chloedenavit** [comment]
Hi @abyot,

I have entered the definitions for the questions. I noticed the pop-up when clicking Complete now lists the questions - That looks great.

The new version of the questionnaire has combined a few questions in order to reduce the number of questions. Could we "hide" some of the questions that are no longer needed, just in case the questionnaire changes back to the original, so we don't have to type them again? If it's not possible, let's wait a couple of days before deleting the extra questions because I think Nicolas is reviewing the document again.

Some other feedback while I was checking the tool: 

- [ ] After the user logs in and goes to the Dashboard App, could we show text that says "Please select a SUN country from the menu on the left."

- [ ] Question 3.1: The tool reads "capacity gaps" but we need it to say "capacity needs". I tried to change this wording in the "level of support" questions but I got an error message. Could you fix these or explain how I can do this myself? 

- [ ] Question 3.2: The last Question now includes a table. Could you make this one the same as for Question 2.4 ?

- [ ] Question 5.1: The questionnaire has changed here, and is asking the agency name twice based on whether there is a co-chair... I think it is better to ask the following questions:
- Has a UN Network Chair been appointed? Yes/No
- Does the UN Network have a co-chairing arrangement? (Please remove the capital C from Co-chairing, which is in the questionnaire but incorrect). Yes/No
- Which UN Network agency(ies) serve(s) as the lead Chair(s)? = This question can have multiple answer options, as we discussed previously.

- [ ] Output 5.4: Could you please add question 5.4 "Has the UN Network developed a resourcing strategy for nutrition" ? as the first question.

Thank you! Let me know if you have any questions!

**Comment by chloedenavit** [comment]
@abyot Sorry for accidentally closing the issue! My mistake.

**Comment by abyot** [comment]
@chloedenavit 

Re: 3.1 "capacity gaps" => "capacity needs" It should be as easy as editing this page

http://109.237.25.74:9091/inventory/dhis-web-maintenance/#/edit/dataElementSection/dataElement/FzEbQCGySPi?_k=3h6yrs

Two things to keep in mind is that - both name and short name need to be unique and also short name can not be more than 50 chars.

I will try to go through the changes we have in the questionnaire. Is it easier for you to mark changed questions in the document? 

I have added sun countries in the system

Re: deleting / hiding questions

Yes, deletion will not be possible if data is already entered for the question. But it is possible to hide.

Just go to Maintenance -> DATA SET -> List -> UN Network Survey -> Right click, Edit

Go **"Data elements"** section, 

Those to the right are assigned data elements to the data set. Search for the data element of interest and move it to the left. It will then be unassigned to data set (or questionnaire).

You should clear your cache to see the effect.

**Comment by chloedenavit** [comment]
Thanks @abyot, I will try to make the questionnaire changes myself and hide the questions we don't need.

Another question for you: In Questions 5.4, we ask for users to enter proportions. I am thinking that it would be much easier for the user if they only need to enter the numerator and denominator, and the system could calculate the proportion itself. Is this something that could be done?

**Comment by abyot** [comment]
Thanks @chloedenavit !

Yes, the system can calculate indicators out of numerator and denominator values. 

But a question for you is how are these going to be entered? Are you expecting both values to be entered in the questionnaire itself. Or are you relying on some kind of general target values for denominator? We can create a separate data set (or survey) for the denominators. This way a single target (denominator value) can be shared across agencies. Or is the denominator specific per agency? Tell me more about the percentage calculation.

**Comment by chloedenavit** [comment]
Every agency will have their own denominator, because it is specifit to that agency's budget in that specific country.

**Comment by abyot** [comment]
I see. In that case we can ask for both denominator and numerator in the same questionnaire.
