### ISSUE TITLE
# 21 General staff (G) rows to be added to Output 5.4.2 and Output 5.4.3

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#23]
Hi Abyot, 

we have been asked to add some rows in the tables in Output 5.4.2 and Output 5.4.3.
There is another category of staff that should be inserted.

- [x] Please add them after the JPO row in both tables. It's seven rows in total: G1, G2, G3, G4. G5, G6, G7.

Thanks!

**Comment by abyot** [comment]
Fixed. You need to clear your browser cache to see the effect.
