### ISSUE TITLE
# 22 "Mark report not-complete"

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#24]
Thanks for the amendments made!
- [ ] Can you please add an explanation to the  "Mark report not-complete" box? when you click on the i icon it says:

view data as tables
mark report complete
mark report not-complete

I guess that's not the purpose of the i icon?

thanks!

**Comment by abyot** [comment]
Yes, left it like that because I am expect you to provide an exact wording for each of the buttons

**Comment by Alisia1** [comment]
OK, so we can name them as follows

- [ ] "Mark report complete and leave the survey". By clicking on this button, users will be directed to the dashboard page.

- [ ] "Mark report non complete" and explain in the definition what this button is for. I remember you explained that it was for measuring how many people completed the survey or something like that? Can you write that explanation in the definition? I will let you know if there is anything to change in the definition.

thanks!

**Comment by Alisia1** [comment]
Hi Abyot,

- [ ] can you please fix this?
thanks!

**Comment by abyot** [comment]
Fixed.
