### ISSUE TITLE
# 23 problem with Data Visualizer

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#25]
Hey Abyot,
I am with the data entry user, and I would like to create a graph related to a question in the survey. As mentioned over skype, when looking for the kind of answer that matches the question selected, I can't scroll below UN Networks supported categories. I can't find yes/no answers and so on.

- [x] Can you please fix this?

Same things for the Organisation Units. I can only scroll down until Kenya.

- [x] Can you please fix this as well?

thanks!

**Comment by abyot** [comment]
@Alisia1 @chloedenavit 

Issues with scrolling in visualizer are now fixed.

**Comment by chloedenavit** [comment]
Thanks for your hard work to fix this bug @abyot !
