### ISSUE TITLE
#28 change the name of the public dashboard

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#29]
Hi Abyot!
- [x] can you please change the name of the global public dashboard into "Global Dashboard (public)"?

Thanks!

**Comment by abyot** [comment]
Fixed. 

One thing you need to be aware is that, a data just entered might not be visible right away in the output modules. The reason for this is the analytics (aggregation) engine need to run first for data to be available for visualization. The analytics engine can be run in two ways: auto scheduled and run every 24 hours; manually whenever a user wants to see data entered immediately.

If you wait for 24 hours, things are ok. However, if less than that - then a user needs to go to Apps -> Reports -> Analytics -> and run it.

Part of the reason I gave data entry users access to report was to give these users a flexibility to run analytics whenever they want. However, this is now removed as per your request.
