### ISSUE TITLE
question layout

### ISSUE THREAD

**Issue by abyot** [abyot/sun-inventory#3]
which one should we pick?

![image](https://cloud.githubusercontent.com/assets/4967749/18985008/14da8724-86f6-11e6-836c-a84dcf28e5f3.png)

or

![image](https://cloud.githubusercontent.com/assets/4967749/18985043/407e5d6a-86f6-11e6-97b8-84cb3c3680d8.png)

or

![image](https://cloud.githubusercontent.com/assets/4967749/18985193/1201bbd4-86f7-11e6-93c7-4b906c780c1f.png)

or

![image](https://cloud.githubusercontent.com/assets/4967749/18985366/ce3fdea2-86f7-11e6-8352-aff9606365e5.png)

For me, it is easier to scroll vertically than horizontally... but you decide.

**Comment by abyot** [comment]
The last one seems better...

**Comment by chloedenavit** [comment]
Yes, I agree that the last one is the best one. Thanks! 
Just in case this question got lost, just a reminder to merge Staff Category and Staff Level to "Staff Category and Level" and we will provide a drop down list menu of options for them to choose.

Thanks!

**Comment by abyot** [comment]
sure, I will be waiting for your final decision on that. I mentioned this somewhere, if we still want to collect by agency  - then we have a problem. But let's wait and see your final questions...

**Comment by abyot** [comment]
Hi @chloedenavit 

I think we have decided on this... and closing.
