### ISSUE TITLE
Add a new section in the Outcomes bar

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#31]
Hi Abyot!
Thanks for the amendments you made. I will discuss with Chloe on Output 5.3 and revert.
In the meantime, as per the document I have sent you, 

- [x] can you please add another section called "Contributions of the UN Network towards achieving nutrition goals and objectives" after Outcome 5?
This section will include two questions. Please look at the last page of the document I have sent you.

Let me know if you have any doubt!

Alisia

**Comment by abyot** [comment]
ok I can add ... a question - can I call this section "Outcome 6: Contributions of the UN Network towards achieving nutrition goals and objectives" ?

This will make it easy to keep the ordering so that section will always come next to outcome 5.

**Comment by Alisia1** [comment]
No, it can't be named Outcome 6 as it is not one of the outcomes of the UN Network results Framework.

- [ ] Can you "tell" the system to place this new section next to Outcome 5?

**Comment by Alisia1** [comment]
dear, I just saw that you called it Outcome 6, probably you did it before receiving my comment..

- [ ] can you please rename it?

thanks!

**Comment by abyot** [comment]
fixed.
