### ISSUE TITLE
Output 1.1.1: level of support (explanation) 

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#32]
In Output 1.1.1:  "Please rate the level of support provided by the UN Network to complete the multisectoral nutrition analysis":

- [x] In the explanation box, can you put the definition of the different levels of support on 3 different rows? Like this:

Light Support: .........
Moderate Support: ...........
Intense Support: ........

I know that Chloe already asked you this and try to fix it herself but it was not possible.

**Comment by abyot** [comment]
fixed
