### ISSUE TITLE
Output 4.1.1: add question

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#33]
As per the document I have sent you, if people answer Yes to the first question in Output 4.1.1, 

- [ ] can you add the question "If yes, please specify which kind of support was provided by the UN Network to establish and/or operationalize national sectoral and/or multi-sectoral nutrition information systems (including surveillance systems)" 

This question should appear before the subquestions "Strengthening sectoral information....Establishment of national, multi-sectoral....etc."

At the moment, it's not clear what the sub questions refer to.

Thanks!

**Comment by Alisia1** [comment]
Ok, what if we include the question "Please specify which kind of support was provided by the UN Network" if they answer YES to Outcome 4..1.1? so that they know what the following sub questions refer to:

1. Strengthening sectoral information systems (including support to conduct surveys)	
2. Establishment of national multi-sectoral information system	
3. Strengthening national multi-sectoral information system

**Comment by abyot** [comment]
I can't just place that as a text. It has to be a question and with answer(s).

If you want to keep  

1. Strengthening sectoral information systems (including support to conduct surveys)
2. Establishment of national multi-sectoral information system
3. Strengthening national multi-sectoral information system

as 3 separate questions, the only option is to work on the wording.

**Comment by abyot** [comment]
Hi @Alisia1 @chloedenavit 

Can we close this?

**Comment by Alisia1** [comment]
yes!
