### ISSUE TITLE
Output 2.2.1: add subquestion

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#35]
In Output 2.2.1, if people answer no to the question "Are dimensions of equity, equality and non-discrimination integrated into these documents? ", another sub question should open up saying "Please explain why the dimensions of equity, equality and non-discrimination have not been integrated into policies, strategies, plans and programmes."

- [x] Can you add it?

Thanks!

**Comment by abyot** [comment]
Fixed.
