### ISSUE TITLE
URGENT OUTPUT 5.3 (JOINT PROGRAMME) NOT COMPLETE

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#38]
Hi Abyot,
I have noticed that the table on joint programmes has not been completed yet...as we would like to launch the pilot today, can you please let us know when this table will be completed?
Thanks,
Alisia

**Comment by abyot** [comment]
It is almost there. The issue is mentioned is never a showstopper. You can go ahead and use it.

**Comment by abyot** [comment]
Hi @Alisia1 

I have made a fix for this. 

Have also added some graphs in the dashboard (the first 4 graphs in Dashboard: Outcome 5).
