### ISSUE TITLE
export the survey in PDF

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#39]
When I tried to export the survey to PDF, it goes directly to the the 'print section'. If you try to exit that page, the system doesn't allow you. You have to click on the arrow on the top left, but then you are sent out of the dashboard page and need to log in again.  Why?

- [ ] Can we fix that?

- [ ] Can we allow our users download it and eventually print it, if they want?

- [ ] Moreover, the PDF opens in the same window as the system. Nicolas would prefer if PDF opened in a different window. 

thanks!

**Comment by abyot** [comment]
This is invalid now.
