### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#4]
- [x] Could  you please change the levels of support to "light support" "moderate support" and "intense support" ?

- [x] Could you rename the UN Network Survey to "UN Network for SUN Annual Reporting"

- [x] Could you change the green button to "Report Complete" and the red button to "Report Not Complete" (I think this will be good enough for now, to distinguish that we mean the _whole survey_ and not just this outcome should be complete)

**Comment by abyot** [comment]
Hi @chloedenavit 

This are fixed now. Please clear your cache if you wanted to test.

I have also upgraded to the latest version of DHIS2.

**Comment by chloedenavit** [comment]
This all looks great,thanks!
