### ISSUE TITLE
notification when the report is complete

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#41]
This is just an information:

When users mark the report as complete, who will receive a notification? Only us or other users too?
How is the system set at the moment? We would like to be the only one to see the notifications and the inputs entered.

thanks!

**Comment by abyot** [comment]
Those users belonging to "Survey Report Supervisors" user group will get the notification. This is customization - one just has to create a user group and assign it to "Complete notification recipients" property of the data set being reported and completed.

![image](https://cloud.githubusercontent.com/assets/4967749/20134168/bdfa535a-a66a-11e6-8dee-a32e8147b9b1.png)
