### ISSUE TITLE
Moving the graphs in the dashbooard

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#42]
Hi Abyot!
One question: I have noticed that any user who logged in can move the graphs  in the dashboards they see (also the global dashboard). 

- [ ] Can we allow countries to change the disposition of graphs only for their own private dashboards and  remove this option for the public dashboards (global and country level)?

We would like to decide the disposition of the graphs in the public dashboards without someone else changing it. 

thanks!

**Comment by abyot** [comment]
Hi @Alisia1,

No, we don't have specific authority for the ordering / layout of dashboard items.
