### ISSUE TITLE
question: program needed to download pdf

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#43]
Hi abyot, 
just a question: what was the name of the program needed to download the pdf of the list of questions and answers in the survey? I am adding a line to the user guide I am writing to inform our users about this possible issue.
thanks!

**Comment by abyot** [comment]
There is no as such particular program for pdf. We expect their computer to have PDF printer.

I would suggest for not emphasizing that feature.

**Comment by abyot** [comment]
I do not have addition information / solution on this.
