### ISSUE TITLE
Additional drop-down menus in green box

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#44]
Please create additional drop-down menus in the green box, as follows: 
1) Organization Unit
2) Category
3) Thematic Area 
4) Type of support: the two options in the drop-down will be 1. Enabling Environment, and 2. Procurement, Logistics, Supply & Service Delivery. 
5) Action

**Comment by chloedenavit** [comment]
Thanks for doing this, I think it will be a good solution for our users to understand the structure of the actions list.  

However, when I click on the Health category and went to select the thematic areas in the next drop-down, the first 4 thematic areas that appeared in the list are actually part of the Agriculture category. Could you please remove these?

**Comment by abyot** [comment]
yes, aware of these issues - working on them at the moment.

**Comment by abyot** [comment]
Thematic areas are not properly filtered based on category.

**Comment by abyot** [comment]
Thematic areas are now filtered based on category.
