### ISSUE TITLE
UN Joint Programme and Nutrition Objective answer options

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#46]
- [x]  Please correct the typo in agencies (adding the i).

- [x] Joint Programme: Please change the drop-down menu answer option for NO to say: "No - Not part of a UN Joint Programme"

- [x] Nutrition Explicit Objective: Please the drop-down menu answer options to:
Yes - Has nutrition explicit objective(s)
No - Does not have nutrition explicit objective(s)

- [x] Aligned to Country National Nutrition Plan: Could you add an answer option called "Not aligned to Country Nutrition Plan"? (I am removing "national" to make it shorter)
In addition, you suggest that you would be able to make it so when they select this, the rest of the answers are deleted from that box. That would be great.

- [x] Aligned to Country Core Nutrition Actions: Could you add an answer option called: "Not aligned to Country Core Actions" (I am removing national to make it shorter)

**Comment by abyot** [comment]
This is fixed. However, instead of objective(s), I have used objective as the '(' and ')' are not playing well with the standard syntax we have in the system. I hope this creates no problem from your side.
