### ISSUE TITLE
Inventory users cannot see Dashboard data

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#49]
Could you please make the Inventory users unable to see the Dashboard content, as you discussed with Alisia?

**Comment by abyot** [comment]
We can do this ... but then we need to better plan / coordinate between the needs to dashboard and inventory.

What we have already done for the dashboard is that there are dashboards and corresponding items that are made public. Public both for the general (without login) and public (only for those who are logged in). Now, we are saying inventory users shouldn't see dashboard stuff... 

We need to decide, either we consider those configured public (both general and logged in public) to be seen by inventory users or we drop the idea of configuring public in dashboards ... or make the systems separate instance. We can't have all.
