### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#50]
- [x] Please move all buttons to the bottom of the data entry page

- [x] Please change the blue button to say "Apply data to geographic areas".

- [x] In the pop-up window that lists the organization units, please add the following instructions above the tree: "Select the geographic areas that this data applies to. All answers will be applied to the areas selected, but this data can be edited later by selecting a specific area from the menu to the left of the main data entry screen." 

- [x] Please change the red button to say "Remove data from selected geographic area"

- [x] Please add a button that says "View data as table" and enable the user to select for which organization units they wish to view data. 

- [x] Please add a green completeness button that says "Mark as complete". I will add this button in my mock-up that I will send you so that you know where to place it.

- [ ] The green and red buttons should not be click-able until all the answers have been filled for the unique identifier combination.

**Comment by chloedenavit** [comment]
Hi @abyot,
I see that when we click on the Complete button, the message in the pop-up still needs to be customized. Could you please use this one:

Have you entered data for every nutrition action that your agency is carrying out? You may need to consult with colleagues in your agency to obtain information on other actions that have an impact on nutrition. If you have fully completed your agency’s inventory, click on Mark data complete. To return to data entry, click on Cancel.

We would then need to name the button on that page this way. If those buttons can't be renamed, please use the correct words in the message above.

**Comment by abyot** [comment]
yes, it is no problem to customize that. You can also send me a text for the buttons if what we have currently is not explaining enough.

Technically, there is no restriction on the length of button texts - but having a short text one or two words will look nice in buttons.

**Comment by chloedenavit** [comment]
OK, thanks. The 2 buttons to exit this pop-up can simply say  "Mark as Complete"  and "Cancel".

**Comment by chloedenavit** [comment]
Hi @abyot, just a reminder not to forget to add a new "Mark as complete" button on the Report tab, since it seems that this summary report will be working out for us. 
Thanks!
