### ISSUE TITLE
"Title" bar in data entry to be edited

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#51]
Hi Abyot! Before our call today, I will send you a list of things that should be changed/added/deleted, so that you have an idea of what's coming.
Here the first issue:

- [ ] Can you make the green bar with the Thematic Area and Action selected for the data entry more like a title? The font should be in bold and as big as the one of the sentence 'Click here to view the full Compendium of Nutrition actions'.
Can you also center the sentence?

Please find attached a screenshot of the bar I am talking about for ease of reference.
![inventory bar to be edited](https://cloud.githubusercontent.com/assets/22884743/20558302/a1507c60-b16f-11e6-8857-64ed5ce39135.PNG)

thank you!

**Comment by abyot** [comment]
sure, we can have this.

**Comment by abyot** [comment]
Fixed. 

![image](https://cloud.githubusercontent.com/assets/4967749/20559976/67aea20e-b177-11e6-916b-0890f8de0cbe.png)
