### ISSUE TITLE
View data as tables button

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#54]
When clicking on the 'View data as tables button' after entering your data, the system does not direct you to another page showing all the data entered so far, like it did for the Dashboard.
It just "freezes" the page you are in, showing only the data visible in that page, without giving you the possibility of exporting the data into excel or pdf.

- [ ] Could we have something like what we had in the Dashboard? We would like our users to be able to see **the whole data** entered so far for a specific Agency in a specific Year, not only the data entered in the page they are in when clicking on the View data as Tables button.

thanks!

Alisia

**Comment by abyot** [comment]
What we have is exactly the same as the one we have in dashboard. There, we display the same data that users see in the screen - of course all tabs merged - but in a different way.

What you are asking here is totally different with lots of aggregation and I think the best place is the pivot table. See below..

![image](https://cloud.githubusercontent.com/assets/4967749/20560491/f276e660-b179-11e6-93a4-c18fb1c7097a.png)

If you think that is not enough, then we need to develop a separate report module.

**Comment by Alisia1** [comment]
Hi Abyot,
Unfortunately the data represented as the table above is not what we want. It's really a lot of data only for one table and it would be difficult to print.
As per yesterday's call, we will let you think of a way to display raw data in a easier way.
Please note that actually not all data entered until that moment need to be displayed, at least those concerning the **Actions**, for a specific **Agency** for that given **Year**.
Please let me know if this is possible.
thanks!

**Comment by abyot** [comment]
The data is the one in the blue table. It lists all actions that an agency has entered data or not.

**We would like our users to be able to see the whole data entered so far for a specific Agency in a specific Year**

Can you tell me more what exactly we need to display here? What if an agency has entered data for more than one region? how do you want to see the output?

**Comment by Alisia1** [comment]
Hey Abyot!
We saw that you created a new section called "report". Thanks!
We assume that it's still under construction as we are not able to generate any report yet...
If this new way to see the reports work out, please remove the View data as table button!
thanks!

**Comment by abyot** [comment]
Yes, that is the new approach and it is under development. 

The button will be removed. I guess one of the green areas at the bottom will also be removed. The remaining three buttons will fit in the left side green area.

**Comment by chloedenavit** [comment]
That sounds good, thanks. 
When you move the completeness button, please make sure it is the last one, and leave a space between the delete and complete button so that users don't accidentally click on Complete. Like this:

Save
Delete

Mark as Complete

**Comment by abyot** [comment]
sure, but are you worried for complete than delete?

In any case, both delete and complete will have a confirmation dialog. i.e. the action will not be triggered in just one click. Users need to confirm with a second click.

**Comment by chloedenavit** [comment]
Yes, and actually I am not really worried about clicking the wrong button, but I am more worried that they won't understand that the top 2 buttons relate to only this action instance, while the Complete button relates to the entire inventory. That's why I'd like them to be physically seperate.

**Comment by abyot** [comment]
Hmm... "Complete button relates to the entire inventory"

We need to discuss this. I mean, as it stands all those buttons are for the action. We don't have a means to fetch all actions in the data entry form. I am trying to get that in the reports section... may be we need to move the complete button to the reports section?

**Comment by chloedenavit** [comment]
Ah, ok. I don't think it's necessary to have Save and also Complete for every action. 
Moving the complete button to the reports section could be an excellent solution - This way, they can see an overview of all the data they've entered and sort of perform a "check" before they submit their entire data.
Perhaps we could still have a button on the action page that says something like "Review and submit report" which would take them to the Reports section? From there, they can review their data and then click on Mark as Complete.

**Comment by abyot** [comment]
yes, sure we can have that link.

**Comment by chloedenavit** [comment]
I will close this issue as we are discussing the "Mark as complete" button in the other issue.
