### ISSUE TITLE
Add definition to "Action Instance" 

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#55]
- [ ] Can you please add an icon with the question mark next to the 'Action Instance', and a definition saying:

"An instance represents one project or programme that supports an action. An action may be supported multiple times by one UN agency if several projects or programmes focus on the same topic. To enter data on an additional project or programme supporting the same action, select a new instance from the drop-down menu and enter new data for this instance."

thanks!

**Comment by abyot** [comment]
Fixed.
