### ISSUE TITLE
Rename buttons and add steps at the bottom of the page

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#57]
We thought that the functions of the buttons "Apply data to geographic area" and "Remove data from selected geographic area" can be a bit confusing.

Instead of having those buttons, we would like to add a sentence and three steps at the bottom of the page, saying the following:

_To assign the geographic focus of the data entered, follow the steps below.

Step 1: Does this data apply only to national level? 
If yes, your data have been automatically saved. You may select the next action you would like to report from the drop-down menu at the top of the screen. 
If no, move to step 2. 

Step 2: Does this data apply to both national and sub-national geographic areas? 
If yes, click on the blue button below to select the applicable areas.
If no, move to step 3. 
< **blue button named Add data to sub-national areas** > 

Step 3: Does this data apply only to sub-national areas? 
If yes, click on the red button to indicate that these data are not applicable to the national level. Your data will remain in the sub-national areas selected in Step 2.  
< **red button named Not applicable to national level** >_ 

- [ ] Can you please add a box with the different steps to be followed and rename the buttons as per the list above?

Thanks!

Alisia

**Comment by abyot** [comment]
Is this valid now?

**Comment by chloedenavit** [comment]
No, we can close this.
