### ISSUE TITLE
Add a sentence on top of the page and turn data entered into green

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#59]
- [x] Can we add a sentence on top of the page saying "Please note that data are automatically saved once entered. Once every question has been answered for an action, simply select a new action from the drop-down list to enter additional data.", maybe in a red box as per the Dashboard?

Do you think we have some space left for adding a new box?

thanks!

Also, even if by adding the new sentence on top of the page our users will know that data are automatically saved, when entering data in the tabs which do not have a drop down list - meaning, the Agencies in UN Joint Programme, Aligned to Country National Nutrition Pla, Aligned to Country Core Nutrition Actions -, data do not turn into green. I know that there is a little shadow behind the element selected which does turn into green to show that data are saved, but it's not really visible.

- [ ] Is it possible to turn the entire name of, for example, the Agency selected, or the Country National Nutrition Plan selected into green? To give the users a stronger sense of data being saved.

The problem arises when deleting the data just entered to fill in another Action Instance.
Even if data already entered won't be canceled, by deleting them it feels like they will, so we would like the users to actually **visualize** somehow that data are saved.

thanks!

Alisia

**Comment by abyot** [comment]
To give users a stronger sense that the data is save, what I can do at the moment is turn the entire background of the drop-down to green. It will turn to red if the saving has filed or yellowish if pending (say for example when there is a slow network and saving is taking time)
