### ISSUE TITLE
Question modifications

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#6]
Hi @abyot,
After Q.1.1 could you add a sub-question, if they say yes, that is a table as the one highlighted in yellow on page 3?

After Q. 3.2.2 could you add a sub-question, if they select yes, that is a table as the one highlighted in yellow on page 10?

I added this question: _3.1.3. Has the UN Network provided support to scale-up sustainable nutrition-specific and nutrition-sensitive interventions and programming?_
But I didn't know which number to put for "Order". I put 3 since the previous question had that. Could you help explain or fix this? 

Question 4.1. I was not able to change the description because when I tried to save, it gave me an error message as the one attached here. 
![transient](https://cloud.githubusercontent.com/assets/21313941/19245905/ef612454-8f23-11e6-80bb-7be0f3d7dcc6.JPG)

After this question, the others questions I tried to modify showed me the same error message. Could you let me know what to do to fix this? 
Thanks!

**Comment by abyot** [comment]
Hi @chloedenavit 

Q1.1 - page 3 from which document? I don't see a table highlighted with yellow in any of the documents I have.

Re: Q.3.2.2 is the same as above.

Re: Q.3.2.2 - order is the position of the question in its output group when all the questions are visible.

I will look into Q.4.1

**Comment by chloedenavit** [comment]
Hi @abyot,

Thanks for adding the question and updating it.

Basically I am going through every question and adding the question number to the beginning (example: 2.1.1) and also updating the question wording and description based on the newest document. I don’t want you to have to make these changes for every single question because it will be tedious for you, it will happen again after the review, and it should be something that I am able to do in the future so I need to learn. 

Many of the questions I was able to modify and to hide, but for a few of them I got an error message. Could we maybe Skype tomorrow so that I can share my screen with you and you can tell me what I’m doing wrong? 

Here are the ones I was not able to modify - highlighted in yellow in here:
[02  UNN Draft Country Dashboard Questionnaire _10102016.pdf](https://github.com/abyot/sun-inventory/files/522532/02.UNN.Draft.Country.Dashboard.Questionnaire._10102016.pdf)

- 4.2.1. Has the UN Network provided support to measure and report coverage of national nutrition interventions?” 
- 4.2.3 Has the UN Network provided support to develop Common Results Frameworks linked to national nutrition plans?
- 5.2.1: Has a UN Nutrition Inventory been fully completed by the UN Network
- 5.3: Are joint UN nutrition programmes in place and currently implemented within the Network?

I will also need to find out some details about adding new questions. But if you don't have time to Skype tomorrow, could you add the following ones (also in yellow in that doc):
- Sub-question until 5.1.1: Has a UN Network Chair been appointed?
- Third sub-question under 5.3: Please indicate areas of joint programming
- Question 5.4.1,2,3 and all of their sub-questions. These are still being discussed by our team so we can discuss on our call on thursday how to do these.

Thanks a lot !

**Comment by chloedenavit** [comment]
Hi @abyot,
I also tried this morning to hide questions in the data set as you instructed me, and I was able to remove one and save the data set successfully. However, when I tried to hide a second question (or multiple), when I tried to save the data set, it gave me an error message: "Could not save data set". I tried hiding different questions but none of them work after this.

I thought it might be because there was already data in some of the questions, so I removed all data that I could find, but it still didn't work.

I want to provide you with fake data as soon as possible so that we can work on the visualisations this week, but we need to first update the questions (content and hiding) to match the questionnaire.

**Comment by chloedenavit** [comment]
Hi @abyot ,

Output 1.1:  Thanks for changing from a table to individual questions. However, I see a problem here because they might not have received support on all three activities. Would it be possible to ask two questions for each activity: 
(Please note that the multi-sectoral nutrition analysis is one of the activities, and also the name of the whole question. I know this is confusing, so I will work with them to change the terminology, but note that it should be treated the same as the policy review and mapping activities.)

1. Please indicate the number of multi-sectoral nutrition analyses that your agency has supported
(The next question appears if they enter more than 0. We can put a maximum of 15 if you need a limit.)
2. Please rate the level of support provided by the UN Network to complete the multisectoral nutrition analyses.

1. Please indicate the number of policy and plan reviews that your agency supported.
If more than 0:
2. Please rate the level of support provided by the UN Network to complete the policy and plan reviews.

1. Please indicate the number of stakeholder and nutrition action mapping exercises that your agency supported.
If more than 0:
2. Please rate the level of support provided by the UN Network to complete the stakeholder and nutritoin action mapping.

1. Please indicate the number of other multi-sectoral nutrition analyses that your agency supported.
If more than 0:
2. Please rate the level of support provided by the UN Network to complete the other multi-sectoral nutrition analyses.

**Comment by abyot** [comment]
sure, we can ask 1, 3, 5 and 7 independently and then ask level of support for each depending what is answered. But seems we are going back to the previous questionnaire we have...

Also, what are the options when asking level of support? We are using both
- Light, Medium, Intense
- Light, Moderate, Intense
which one should we use? or are we planning to use both?

**Comment by chloedenavit** [comment]
OK, cool. Do you think you can work on those questions this morning? I will go through the paper questionnaire and compare it to the web-based version so that we can spot any remaining inconsistancies. I'll then send you a list of stuff to fix through git hub if there is anything remaining, before we enter data.

The levels of support should always be "light, moderate, intense". If you saw medium somewhere in the Word questionnaire, please let me know so that I can fix it in the Word version, because that is our mistake.

Thanks!

**Comment by abyot** [comment]
Will try to work on these questions very soon. Right now, away from computer:(

The new tables you had in yellow talk about medium.

**Comment by chloedenavit** [comment]
Yes, that is a mistake on our end. It should aways say "moderate". Thanks for catching that!

**Comment by chloedenavit** [comment]
Hi @abyot ,
FYI we are now enterring data for 6 countries we chose: Cambodia, El Salvador, Kenya, Burkina Faso, Nepal, Peru, Myanmar. It will be done before 6pm today.
I look forward to seeing the visualisations tomorrow during our call, it'll be nice to see some "outputs".
Thanks!

**Comment by abyot** [comment]
perfect, I will generate some outputs after 6pm today. 

I was fixing some issues when editing questions - it should be fine now.

**Comment by chloedenavit** [comment]
Hi @abyot,
Here is a list of changes that either I tried to make myself but could not succeed, or I don't know how to do it myself. If possible, could you make these changes before the call? If not, the visualizations and changing the tables under 5.4 are more priorities. But these changes would be great 👍  

- [ ] Output 1.2.2.: After answering YES/NO, there isn’t the box asking about the level of support provided (as per the questionnaire). It goes directly to the question asking for the description of the contribution.

- [ ] Output 2.2.: I don’t think the hiding Assign/Remove feature in Data Set is working for me. For 2.2, variations on the same question are showing many times even though I have tried to hide them, and the sub-question appears 4 times in the “ Assigned” list but doesn’t show up in the series of questions… I wish I could fix this myself, but in the interest of time, could you make sure the questions in this Output reflect the questionnaire? 

- [ ] Output 2.4: The first question is missing its numeration (2.4.1)

- [ ] Also Output 2.4: The table below needs to be removed entirely (the one that starts with "develop resource mobilization strategies). Or you could hide it, in case we end up needing it in the future...

- [ ] Output 5.1.2: The sub question below the 5.1.2 needs to be removed. And it should be replaced with the free text question: Please briefly describe the UN Network’s involvement and activities this past year towards Output 5.1 (UN Networks in place and functioning).

- [ ] Output 5.2.2: The last sub in the questionnaire needs to be added: It’s a free text box with the following question: Please briefly describe the UN Network’s involvement and activities this past year towards Output 5.2 (Country UN Network Strategy/Agenda aligned to national priorities, plans, and joint UN framework).

- [ ] Output 5.4: When you change these tables, please note that there are two staff questions (5.4.2 and 5.4.3) with slightly different question names and definitions, but the exact same tables can be used for the both. 
There are also 2 financial questions, but you’ve already done that online. 

- [ ] 5.5.3.: The questions are phrased a bit differently that in the Word questionnaire on purpose, I changed them myself. Howeve, the last question is a table but we don’t want a table anymore. For quicker data entry, we are now only asking for one number  (See questionnaire).

- [ ] A few people in our office have been confused by the red asterisk, since all the questions are compulsory. Could we instead change the asterisk to black, and only include it next to questions that have definitions? We could then add to the green box of instructions: " Click on each question with an asterisk to view its definition. Click on the question again to hide the definition. "

Other things we could discuss during our call tomorrow: 
- Reports: Can we set these up so that the system administrator or the country can download a report (Tables) of their results? 
- Could we also talk during the call about the visualizations for a single country and how they would look? 
- Logo: You can see then when we share screens during the call, but right after logging in, the logo looks huge for a second before returning to normal size on the top left, which makes the website seem like it has a bit of a glitch... Should we reduce its size or do something else to fix that ? 

Thanks for everything ... talk to you tomorrow.

**Comment by abyot** [comment]
Hi @chloedenavit,

- logo is scaled down
- visualization for sample country - Cambodia - is now available under outcome 5
- the tables in 5.4 are now restructured as per the discussion

I will go through the items you listed sometime tomorrow.

**Comment by chloedenavit** [comment]
The graph for Cambodia looks awesome- thanks a lot. 

The tables in 5.4 are exactly what I had in mind. Two things need to be changed (not necessarily before the call, as they are not so urgent):
- The row that says REACH and International Cluster Coordinators. Could you divide this into: 1) REACH International Facilitators; 2) International Cluster Coordinators.
- There is a second staff question that says almost the same thing but is different. Could you add another table with the same options, but with the additional question that is in the questionnaire? 

Also, at some point we changed the order of the Levels of Support (to test the colors, i think) and I would like to change them back to the logical order: Light, Moderate, Intense. But I can't remember how to change the order myself. Could you do that?

**Comment by abyot** [comment]
Latest changes: 
- REACH International Facilitators & International Cluster Coordinators are in place
- The second table in 5.4 about staff is added
- Order of Light, Moderate and Intense is respected. You can control this by going through Maintenance -> Category -> Support Level -> Edit (here you can do ordering)
