### ISSUE TITLE
Move the Organisation Unit bar to the bottom

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#61]
Hi Abyot,
as per yesterday's call, I am going to send you the list of amendments we agreed on, plus some other changes we'd like to make.
Here the first one:

- [ ] Can you please move the Organisation Unit bar to the bottom of the green box which includes the Category, Thematic Areas etc..?

We agreed that the list of countries and regions/districts will be shown in a pop-up window that will show up when trying to enter the Org Unit.

Thanks,

Alisia

**Comment by chloedenavit** [comment]
Hi @abyot,
Now that they are only going to choose their country as the Org Unit, and choose the region "tags" as the first question, we need to move the Org Unit drop-down. 
Would it be possible to move it to the blue box, along with year and agency (as the first drop-down, above these two)? 
Could we make this remain filled even when actions/instances are changed?

**Comment by abyot** [comment]
Now moved to the right. A country is selected by default. The way this works is that ...

The system allows for a user to have access more than one country (or in the systems terminology hierarchy of organisation units). By default, the system select the one of the root countries (organisation units). 

If a user has access only to one country - which was mentioned repeatedly - then no additional selection is needed as this country will be picked automatically. A selection will be needed is a user has access to multiple countries and the one selected by default is not the country of interest at the moment.
