### ISSUE TITLE
 add "save" button, remove the red box at the top, empty the Action Instance bar

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#62]
Here three amendments that are strictly connected:

- [x] Can we add a "save" button at the bottom of the data entry page?

- [x] Can we then remove the red box at the top of the page?

- [ ] After clicking on the "save" button, is it possible to clear all data just entered for that section **together with** the Action Instance bar - which will not show automatically Action Instance 1 anymore, it will just be empty - ?

Thanks!

**Comment by chloedenavit** [comment]
Hi @abyot, Just wanted to double check with you if it will be possible to require that all questions are answered before clicking on Save, except the question about UN agencies in UN Joint Programmes, which can be left blank. 

Second question: After you click save, can the user edit and resave to override the previous save?

**Comment by abyot** [comment]
Hi @chloedenavit ,

Right now the system will not saving anything as I am restructuring the entire data entry workflow. Otherwise, yes it is possible to force for all questions to be answered before saving...

The second question is tricky... the "resave" and "override" could be in different states. The problem is since there are multiple states - we need to chose and decide on which one to act (this was the other mail I wrote about).

**Comment by chloedenavit** [comment]
OK, maybe we can discuss this on the phone. Thanks!

**Comment by chloedenavit** [comment]
Hi @Abyot, I notice that when the text box is filled with a description, it never turns yellow like the other answers do. I know this is a different data format, but am wondering if we can turn it yellow when someone types something, or after they click "save" so that it is consistent with how the other data selection boxes react.

**Comment by abyot** [comment]
sure we can have this ...

**Comment by chloedenavit** [comment]
Can you make the following question NOT required before saving: "If so, which UN agencies are part of this UN Joint Programme? etc...
If they say no to the previous question, we expect that this one will be blank.

**Comment by abyot** [comment]
I see.. then a proper solution would be to add an N/A to the agency list so that they can select this when their answer to the previous question is no.

**Comment by chloedenavit** [comment]
ok, that sounds fine. 
Then we'll also need to change the wording of the question itself to say "If not, please select N/A"  instead of "leave blank". Could you please make that change as well?

**Comment by abyot** [comment]
sure, I will fix that but the change will come a little later as I have to rebuild and deploy the entire system. For now, I have added N/A to the agency list. It should be visible if you clear your cache :(

**Comment by chloedenavit** [comment]
ok, no problem. thanks!

**Comment by chloedenavit** [comment]
We didn't discuss how to deal with the "saving"  of the data if there was already data previously saved for this unique combination. I would recommend that if there is already data saved there, then a pop-up will be generated, warning the user that previous data was already saved for this action instance, and asking them to confirm whether they want to replace that data. They can then say "Save" or "Cancel". 

And to go a bit further, would the system be able to recognize whether the data being saved the second time MATCHES the data that was saved the first time, or is different? We could have this pop-up message only come up if the data is different (does not match the previously saved data).

Thanks for your inputs.

**Comment by abyot** [comment]
This won't be a problem or did you found it problematic?

Every time you pick a combination of keys (country, action, agency, instance, year), the system checks if there is data already saved. If data exists, it displays the data and you are free to edit and of course save it by clicking the save button. 

If there is no data for the selected key combination, the system displays empty form.

**Comment by chloedenavit** [comment]
?OK, I understand. So anytime you click save, it just replaces the previous data with the new data. That's fine, thanks!

________________________________

**Comment by abyot** [comment]
Yes.
