### ISSUE TITLE
Question on Agencies in UN Joint Programme

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#63]
- [ ] If selecting "No - Not part of a UN Joint Programme" in the question referring to the joint programmes, is it possible to turn the following question - Agencies in UN Joint Programme - into grey, so that users understand that that question is obviously not to be taken into consideration.  

- [ ] If the above option is not possible, can we add the option "None" to the agencies list?

It's just to make the sequence of the question about the Joint Programmes, and the following question about the agencies, more logical for those users that have replied "No" to the Joint Programme question.

**Comment by abyot** [comment]
Hi @Alisia1 @chloedenavit 

For technical reason - especially for generating report - the one filling the data has to always be filled in the Agencies list. If this creates a problem for you - or affects the way reports are processed and interpreted - we need to discuss a way to handle this, I have some ideas...

**Comment by chloedenavit** [comment]
Just to double check - is it possible to grey this question out (user can't select answers) if the previous question is answered with NO? Sorry if you've already answered this and I've forgotten..
If this isn't possible, you can just close this issue.

**Comment by abyot** [comment]
Sorry, not possible to have a skip logic in the current model and workflow.
