### ISSUE TITLE
Edit the text of the questions/answer options in the Data Entry page and add definitions

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#64]
Can you please change the wording of the questions and the related answers, and add some definitions to them?

1. Turn "Size of investment£ into "What is the size of your agency’s investment in this action instance?"

- [x] change the answer options to include the dollar amount so that they see it directly. 

- Small (< 50,000 USD)
- Medium (50,000 – 100,000 USD)
- Large (100,000-200,000 USD)
- Very large (> 200,000 USD)

- [x] Please add the Information icon and this definition to the question:
_Indicate the approximate range of  funding secured for this action instance, in the year being inventoried. If one amount of funding is supporting several action instances, divide the amount of funding by the number of action instances supported. For example, if a project worth $100,000 is supporting both Complementary Feeding and Biofortification, the amount of funding should be divided by 2 and both actions should indicate $50,000 as their investment size._

2. Turn "Nutrition Explicit Objective" into "Does this action instance have nutrition explicit objectives?"

- [x] Add an information icon that they can click on to reveal a definition:
_An action instance is considered nutrition explicit if nutrition is included in the objectives of the project, or if the M&E framework includes nutrition indicators._

3. Turn "Part of a UN Joint Programme" into "Is this action instance part of a UN Joint Programme?"

- [x] Add an information icon that they can click on to reveal a definition:
_Please include only official UN Joint Programmes where an MOU has been signed. A UN Joint Programme is a set of activities contained in a joint work plan and related common budgetary framework, involving two or more UN organizations and (sub-) national governmental partners, intended to achieve results aligned with national priorities._ 

4. Turn "Agencies in UN Joint Programme" into "If so, which UN agencies are part of this UN Joint Programme? If not, please leave blank."---> this question will be changed in case it can turn into grey if answered "No" to the previous question or the option "None" can be added to the list of possible answers.

- [x] Add an information icon that they can click on to reveal a definition: 
_Please include only UN agencies with whom an MOU has been signed. Please include your own agency in the list._ 

5. Turn "Aligned to Country National Nutrition Plan" into "Please specify if this action instance is aligned to an objective/result in your country’s National Nutrition Plan.

- [x] Add an information icon that they can click on to reveal a definition:
 _If the action instance is not aligned to an objective/result, please select “Not aligned to Country Nutrition Plan._ 

5.	Turn "Aligned to Country Core Nutrition Actions" into "Please specify if this action instance is aligned to one of your country’s Core Nutrition Actions".

- [x] Add an information icon that they can click on to reveal a definition:
_If the action instance is not aligned to one of your country’s core nutrition actions, please select “Not aligned to Country Core Actions._

------

- [x]  we should add information icons next to Category, Thematic Area, Type of Support, and Action drop-down lists. All of them can tell people to review the CAN to understand the lists: 
_Review the Compendium of Actions for Nutrition (CAN) framework, categories, thematic areas, actions and sub-actions by clicking on the icons to the right._ 

Thanks!

**Comment by abyot** [comment]
Fixed. 
![image](https://cloud.githubusercontent.com/assets/4967749/20597475/2f93b576-b244-11e6-9c1d-272aaa436233.png)

**Comment by chloedenavit** [comment]
Thanks @abyot ! 

I know we asked you to remove the instructions above the questions previously, but now that we have definitions I think it’s important to tell users that they exist and how to find them:
“Click on the questions below to view their definitions.”

Format: Could you use the same font and size as the questions? The colour of the box can be a pale red such as R 223 / G 168 / B 165 or similar.

**Comment by abyot** [comment]
Do we still need "Click on the questions below to view their definitions" instruction? We have now info icon next to each question.

**Comment by chloedenavit** [comment]
You're right, I think we don't need it if we have icons.

However, could you make the information icons a bit smaller? Similar to how they look in the SUNPMT?
It would look a bit cleaner if they were the same height as the height of the text. Same thing applies for the ones in the green area.

**Comment by chloedenavit** [comment]
Hi @abyot, just following up to see if you can make the information icons smaller - similar to the ones in the Dashboard would be fine. Thanks!

**Comment by abyot** [comment]
Hi, it is two different things:

1. when making what we have the same as SUNPMT

![image](https://cloud.githubusercontent.com/assets/4967749/20963246/f1b79ea6-bc6c-11e6-96e9-c0a5aa85f7d8.png)


2. when changing icons to have same size as text

![image](https://cloud.githubusercontent.com/assets/4967749/20963347/4df6add8-bc6d-11e6-960b-ba454215589d.png)


which one?

**Comment by chloedenavit** [comment]
Thanks - let's do a combination: The size of the SUN PMT (a bit bigger than text size) and the color of the Dashboard ones (black). We appreciate it !

**Comment by abyot** [comment]
Here it is

![image](https://cloud.githubusercontent.com/assets/4967749/20964851/8273d422-bc73-11e6-9273-2299b6d4fbb0.png)

**Comment by chloedenavit** [comment]
Much better, thanks!

**Comment by chloedenavit** [comment]
Could you also reduce the size of the question mark icons next to the Category, Thematic Area, etc. so that it matches the size of the information icon ?
I think that these icons seem bigger than the information icon. Let me know if it is just an optical illusion...

**Comment by abyot** [comment]
Fixed.
