### ISSUE TITLE
Question wording

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#65]
- [x] The question called "Agencies in UN Joint Programme" still needs to be changed to: "Is this action instance part of a UN Joint Programme?"

- [x] The following question must be changed to: "If so, which UN agencies are part of this UN Joint Programme? (You must include your own agency in this list). If not, please leave blank."

- [x] Please add a new questions a the first one above the others, called "Please indicate the geographic focus of this action instance"

- [x] This new question will need a definition, and I would like us to "hard code" it so that we can have two seperate paragraphs, but it may change so please don't do the hard code yet. I will consult with my colleagues and get back to you. 

_National: Select this geographic area if your agency's support to this action instance targets every sub-national area in the country. National level can be selected regardless of whether all of the target beneficiaries in all sub-national areas were actually reached. 
Examples: Industrial food fortification, vitamin A supplementation, vaccination campaigns, transporting medical supplies to every region, developing a national nutrition policy, etc. 

Sub-national: Select sub-national geographic areas if your agency's support to this action instance targets selected sub-national areas, but not the country as a whole. Sub-national areas can be selected regardless of whether all of the target beneficiaries in this sub-national area were actually reached.
Examples: Developing a regional nutrition plan, providing food assistance to flood-affected areas, training health workers in targeted regions, etc.

Both: If your action instance included national components as well as sub-national components (e.g. a national plan accompanied by pilots in two sub-national areas), you may select both national and sub-national areas._

**Comment by abyot** [comment]
The wording is ok, we can have that. 

However, I have a concern on the national, sub-national and both thing suggested.

What does **"Select sub-national geographic areas"** means?

Are we diverting from discussion we just had and excel report template we went through where we have National, Region 1, Region 2...? 

What kind of report are we expecting?

Can't we have just one question with options "National", "Region 1", "Region 2".. ? It is possible to multi-select, and users are free to chose any.

**Comment by chloedenavit** [comment]
Hi Abyot,

Don't worry; your understanding is correct - We do want to have only one question with options "National", "Region 1", "Region 2", etc.

The 3 paragraphs of definition should belong to that one question. I want to help people understand when to select "national" and when to select "region 1" (a sub-national level) from among that one dropdown list. I am not using the words "choose regions" in the definition because it will not always be called a region, but sometimes be districts, departments, etc.

Does that clarify?

_____________________________

**Comment by abyot** [comment]
ok good, but not sure how the description for "Both" is going to help.. they can select multiple - more than 2 - then what is both here? Also, when saying sub-national, are we implicitly assuming Region 1,... are all sub-nationals? 

I have updated the server with the work in progress data entry UI...

**Comment by chloedenavit** [comment]
Thanks for your feedback. To me, "both" means that they can select National and also selection Region 1. National means they should select the " National" option, and sub-national means they should select region 1, region 2 (or district 1, district 2 - depending on the name of the admin unit in that country).


Yes, we are assuming region 1, region 2 will always be sub-national. They will never be asked to select multiple different countries.


Do you have suggestions of how I could make these instructions more clear?


________________________________

**Comment by chloedenavit** [comment]
Do you still see an issue with this definition or does it make sense? I am not telling people to fill different questions, I am just explaining what we mean by "national"  and specifying that they can also select "national" as well as countries - and in which cases they should do this. 

If it's clear, we can close the issue.

**Comment by abyot** [comment]
not really sure, for me both means I see two things and select both them. in any case this is not really critical, I mean if you or any of your user experts deem the definition not confusing, it is fine with me.
