### ISSUE TITLE
Question on location of green box

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#67]
Hi @abyot, quick question: 
Is it possible to allow users to FIRST use to the blue drop downs (org unit, year, agency) and SECOND use the drop-downs in green (category, action, instance, etc.). I think it makes more sense for users to choose the blue drop-down info first. 

If this is possible, could we swap the locations of the blue and green areas? What I mean is to move the blue and yellow sections to the LEFT of the screen, and move the green section to the RIGHT of the screen?

If this is not possible, could you quickly list for me the order in which people need to use each of the drop-downs?

**Comment by abyot** [comment]
Interesting that you are thinking of selecting country first..., I would be happy if we could follow the following:

- Select country
- Select Category -> Thematic Area -> Support type
- Select action
- Select year
- Select agency / instance

You can also come up with a different order... but keep in mind the following - Action needs to be selected before selecting agency/instance/year

Selecting a country first before selecting anything else gives maximum flexibility. Yes, you have said all countries are filling the same list of actions ... but for some reason if you want few countries to fill a special inventory list of actions then selecting a country first is the solution.

**Comment by chloedenavit** [comment]
?OK, thanks for the explanation. That is fine, but could you do the following:

- move the Country to be placed before the Category (in the green box)

- make the Year and Agency questions be always visible (right now I don't see the Agency drop-down until the Action has been selected).


________________________________

**Comment by abyot** [comment]
I can move country to the right and place it at the top. However, showing the Agency drop down - or even the label - before an action is selected is not possible. 

Agency and Instance come from the category combination that was assigned to an action. To display the categories, I need to know the category combination that only comes after know an action.

**Comment by abyot** [comment]
Hi @chloedenavit,

I am not sure what to address from this issue

**Comment by chloedenavit** [comment]
@abyot I think the conclusion is that my request wasn't possible, so the solution you have come up with will work fine. No need to make any changes here. Thank you.
