### ISSUE TITLE
Editing the Agency drop-down options

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#68]
We would like to remove REACH from the Agency drop-down list (across the whole system - REACH should never be one of the agencies). 

Can we simply delete it from the Maintenance page called Data element category option management ?

**Comment by abyot** [comment]
Yes and refresh you browse cache.

**Comment by chloedenavit** [comment]
When I deleted REACH the following message appeared: 
Could not delete due to association with another object: DataElementCategoryOptionCombo

I then went to the Category Option Combination page and searched for REACH. The different options came up but I could not delete them, only edit them. 

What should I do there?

**Comment by abyot** [comment]
ok, I will take a look.

**Comment by chloedenavit** [comment]
Hi @abyot, any feedback on this?

**Comment by abyot** [comment]
Hi @chloedenavit 

REACH is removed from the Agency list (the one filling). It was not removed from the joint program list because there is some data registered for it.

I can remove both the data and agency (REACH) if that is needed.

**Comment by chloedenavit** [comment]
Sure, you can delete the data and the agency REACH. Thanks!

**Comment by chloedenavit** [comment]
But why didn't it work for me? Is there something else I will need to do when adding / removing others? Or did you just need to fix something in the system?

**Comment by abyot** [comment]
sorry forgot this one. it didn't work for me to when trying to delete. what I did was removed REACH from the list. I can do the same from the Joint. programme agency list as well. And latter delete it from the db (including its related data)

**Comment by chloedenavit** [comment]
OK. How do I remove agencies from the list? I want to be sure I can do it myself when I need to edit this list later.

**Comment by abyot** [comment]
For our setting:

1. Agency is modeled as category option
2. We have agency in two places - in category "Agency" and in category "Action inventory diemension"
3. You can remove agency from the corresponding category
4. For those agencies that can filled as value (for example to be filled in Joint program question), there is addition list that we need to remove from
5. This addition list is modeled as category option group with name "If so, which UN agencies are part of this UN Joint Programme? (You must include your own agency in this list). If not, select N/A."
6. Remove the agency fro this group list.

**Comment by chloedenavit** [comment]
Hi Abyot,
In the Category Options Group, there is no group with that name. 

There are others with similar names: "Agencies in UN Joint Programme" and also "UN Agencies involved". I have added more ageny names (more category options) into both of these lists, but I don't see them appear in the table where you enter data for joint programmes or for budget.

Could you help?

**Comment by abyot** [comment]
There is  category option group with name "If so, which UN agencies are part of this UN Joint Programme? (You must include your own agency in this list). If not, select N/A."

http://109.237.25.74:9595/unnutritioninventory/dhis-web-maintenance/#/edit/dataElementSection/categoryOptionGroup/w9jus4LeoRn?_k=zxvq4v

**Comment by abyot** [comment]
Hi @chloedenavit 

Any issue to address on this one, or can we close?

**Comment by chloedenavit** [comment]
Ok, I figured it out. I was looking in the Management App of the Dashboard instead of the Inventory, that's why I didn't see the correct option group name. Thanks, we can close.
