### ISSUE TITLE
Reorganizing the actions

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#69]
Hi @abyot,
The final version of the CAN (list of actions and sub-actions) is available in PDF version here: http://www.reachpartnership.org/documents/312104/e7029e09-d3ae-49e8-b0e1-24d7bb751b0c

Could you use this list to reorganize the way in which the actions appear in here? Or is this something you'd like us to do?

Also, I would like to input all the sub-actions as well (that will appear in the yellow "tree" area now). Could you let me know how we can do this?

**Comment by abyot** [comment]
Hi @chloedenavit,

That is a long list and would be nice if you could help me in creating the order and sub-action linkage. I can provide guidance on how to do this.

**Comment by abyot** [comment]
Hi @chloedenavit @Alisia1 

I have made the system ready to display ordered actions / subactions, see below:

![image](https://cloud.githubusercontent.com/assets/4967749/20746329/9fe46d0c-b6e5-11e6-8929-cfe37cd3b12b.png)

We need to do the following:

1. Edit all actions to match the order in the pdf document. This can be done by going to Apps -> Maintenance -> Data set. The important parts are:
- each action's name should start with a number as in the document. If this is something you do not want to have, make sure to fill to put the corresponding number as order
- each action needs to have code. It is possible to have any pattern but I would recommend AC1, AC2, 
- do not remove the text (thematic area / support type) after the " - " symbol !

2. For each action, create a sub action. This can be done by going to Apps -> Maintenance -> Other -> Option set
- create new option set for each action - [name: can be the same as the action name that you have the pdf document, here no need to worry about the text after " - ", code: needs to be the same code that was assigned to the corresponding action while editing the data set / action, value type: Text, Option type: SUBACTION]
- then for each option set, create options that correspond to the sub actions. [name: same as sub-action name, code: 1a or 1b or ... which you can take from the sub-action name]

Do this for one or two actions, clear your cache and see if the system has picked the sub-actions. If things are in place, you can go ahead and complete the rest.

**Comment by Alisia1** [comment]
Hi Abyot!
I have tried to reorganize the way in which the actions appear in the Inventory. We don't really want to see each action starting with a number, so I tried to put the corresponding number (1, 2, 3..) as order, as you suggested. 
I went do Apps -> Maintenance -> Data set.
I went to the Action I want to reorganize, namely **"Trade"**, which can be found by matching the below elements:

1. Category:  FOOD, AGRICULTURE AND HEALTH DIETS
2. Thematic Area: Livestock and Fisheries
3. Support: Enabling Environment 

As the Action's number in the PDF is **6**, I gave the Action the code AC6, then I scrolled down to "Order" and I entered 6. 
I Saved, cleared my cache and refreshed. Unfortunate, the order did not changed. 
Can you please let me know what I did wrong?
Please find attached the screenshots of what I have done, for ease of reference. 
Thanks!
![capture for abyot - oder of trade n 6](https://cloud.githubusercontent.com/assets/22884743/20882699/7c8cf1de-bae2-11e6-9684-35f6fb95996f.PNG)
![capture for abyot 2 - oder of trade n 6](https://cloud.githubusercontent.com/assets/22884743/20882700/7ca61dee-bae2-11e6-8ce6-b81272706bbe.PNG)

**Comment by abyot** [comment]
Ordering should be working now.

**Comment by Alisia1** [comment]
thanks!
so what I did was correct? can I continue with the other actions?

**Comment by abyot** [comment]
Yes, absolutely. please go ahead and order the rest as well.

We also have the other issue - linking actions with sub-actions. 

While editing data sets for the order, also assign their code AC1, AC2, AC3,... that way you won't have to edit the data set again.

**Comment by Alisia1** [comment]
OK, you mean that I should give the sub-actions the same code as the action they refer to?
If one action has two sub-actions, will both sub-actions have the same code, as the action they belong to?

Also, we would like to reorganize the way in which the Category and Thematic areas appear in the Inventory. Where can we found them?
Is the process the same as per the actions?

thanks

**Comment by abyot** [comment]
Yes, give the sub-actions the same code as their parent action.

When you say "one action has two sub-actions" - can you give me an example?

The discuss we had last time was for an action to have only one list of sub-actions. One thing to keep in mind is Sub-action can have as many list as needed.

**Comment by chloedenavit** [comment]
Hi Abyot, 
Yes - there is indeed only 1 list of sub-actions for every 1 action. However, since it is a _list_, it has a few items in it. They can be considered one element because they will always be displayed together when 1 action has been selected. 

For example, the action _Management of severe acute malnutrition (SAM)_ has the following sub-actions:
1a. Outpatient management of SAM
1b. Inpatient management of SAM

When a user selects the action Management of SAM, the two sub-actions should always be displayed in the yellow area to the left of the screen. 

Hope this clarifies. Thanks.

**Comment by abyot** [comment]
Yes, that is clear and we have the system ready for this. We only need to create the sub-actions and link them with their corresponding action. Following step 2 (I mentioned in the beginning of this issue) should be enough.

**Comment by Alisia1** [comment]
Dear Abyot,
can you please let me know about this:

_Also, we would like to reorganize the way in which the Category and Thematic areas appear in the Inventory. Where can we found them?
Is the process the same as per the actions?_

thanks!

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
Opening up this issue because I need to add the sub-actions with the instructions you gave us here.
