### ISSUE TITLE
New modification requests 

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#7]
- [x] 5.4.2.: Add the title “Agency” as a title above the columns of agency names and add the title “Level of staff” on top of the left column containing the levels of staff.
- [x] 5.4.2.: Change the words DEDICATED TO to capital letters. In 5.4.3. make the word CONTRIBUTING TO in capital letters.
- [x] Remove all red asterisks.
- [x] Add an information icon to all questions that have definitions. In addition, could you add them to all the "level of support" questions since I need to add those definitions?

_I can't do this specifically to "level of support" questions, instead generally for all with description. Those without description won't have the icon. So when definition is added to "level of support" questions, they will have the icon, until then they won't._ 
- [x] Instructions box: We will send you a mock-up of the colors we want, but in the meantime would you please modify the text to the following: "Click on questions with an information icon to view their definition. All questions in every Outcome must be answered before submitting the report. 
- [x] Output 3.2.2. Please add the Yes/No question before the activities are listed.

_How exactly? What is the wording of the question? Just one Yes/No question for all or each having own yes/no?_

**Comment by chloedenavit** [comment]
Thanks @abyot !

5.4.2.: Thanks for adding titles to the row and column headers. However the diagonal line cuts through the words. Any ideas on how we can improve this? 
Also, could you change UN staff to "Staff Levels" ? 
Finally, the question in bold is along the y-axis and it's very hard to read since it's vertical. Could you move it to be a horizontal line above the names of the agencies? 

Level of support: No problem, it's actually great that the Icon is automatic in case we add or remove definitions in the future.

- 3.2.2: The questions should be the following:
1. Main question in bold: leave as it is now. 
If Yes, the following should appear:
2. Has the UN Network provided support to establish COI guidelines and/or policies? Yes/No
3. (If Yes:) Please rate the level of support provided by the UN Network to establish COI guidelines and/or policies: Light/Moderate/Intense
3. Has the UN Network provided support to mitigate COI issues and/or facilitate COI dialogue among stakeholders? Yes/No
4. (If Yes:) Please rate the level of support provided by the UN Network to mitigate COI issues and/or facilitate COI dialogue among stakeholders: Light/Moderate/Intense
5. Has the UN Network provided support to address other COI issues? Yes/No
6. (If Yes:) Please rate the level of support provided by the UN Network to mitigate COI issues and/or facilitate COI dialogue among stakeholders: Light/Moderate/Intense

**Comment by chloedenavit** [comment]
- [ ] The name UN Staff still needs to be changed to "Staff Levels". 

- [ ] Thanks for removing the diagonal line. However, would it be possible to add a row above all of the agency names, so that it says UN Agencies horizontally across the top of the table? 

Thanks!

**Comment by abyot** [comment]
Hi @chloedenavit 

Staff was changed to "Level of staff" as per your suggestion 3 days ago. You need to clear your cache to see the change.

![image](https://cloud.githubusercontent.com/assets/4967749/19433207/06367936-9460-11e6-8b8f-2daff98fee96.png)

What should be called exactly? You can also give any name you want by going through Apps -> Maintenance -> Category -> Level of staff -> Edit 

Also, I have't removed the diagonal line as you can see from the picture. Do you want it to be remove? Yes, there are problems with it as there could be some overlaps when viewing in different screen sizes...

**Comment by chloedenavit** [comment]
Oh, I'm sorry. In my screen today the line didn't show up, but on my home computer this weekend it did... To avoid the issue of the diagonal line cutting across words in smaller screens, would a potential solution be to put the title in the row above the agency names?

**Comment by abyot** [comment]
We can do that ... but how about for the "Level of staff" ?

Can you have a mock-up?

**Comment by Alisia1** [comment]
HI Abyot,
this is Alisia!

As discussed, we've prepared a mock-up of the instructions box. We have tried different combinations of colors and we think the one below is the best.


![instructions box mock-up](https://cloud.githubusercontent.com/assets/22884743/19436957/72b30e04-9473-11e6-90eb-06a6233ebea0.jpg) 

- [ ] Would it be possible to change the color into this one? Thanks!

- [ ] Also, we thought that we don't need the instructions box in each Outcome page, as the users will understand the instructions the first time they read them in the first Outcome page (when they start the survey). Is it possible to leave it only in the first page so that we can see how it would look that way? Thanks!

- [ ] Last request: we have noticed that the title in the top tab on the left doesn't match the title of the survey. It says "Sun Survey Entry" but it should say "UN Network for SUN Annual Reporting Exercise". I remember that we discussed about this during our call on Friday. Could you please change it? Thanks.

Regards,
Alisia

**Comment by abyot** [comment]
Thank you Alisia. Will fix them all. 

Re: description only in first outcome... in that case we will be assuming users will always pass through the first outcome. Are you OK to have this assumption?

**Comment by Alisia1** [comment]
Hi Abyot,
I just changed the previous comment as we thought that it would be better to keep the instructions box in each page. Please just turn it into red. Thanks!

**Comment by abyot** [comment]
Tab label and color to instruction box are now fixed.

**Comment by abyot** [comment]
Also, diagonal line is removed and a row on-top is added for the agency. Nothing has been changed for the staff level.

**Comment by abyot** [comment]
![image](https://cloud.githubusercontent.com/assets/4967749/19440280/a2992816-9481-11e6-99dd-9b80e7918171.png)

**Comment by Alisia1** [comment]
- [ ] Could you please add the word "UN" before the word "Agency" in the top row you have just created?

- [ ] Also, could you create a "title" for the column on the left as well, inserting a box on the top saying "Level of staff"?

**Comment by abyot** [comment]
This is fixed.
