### ISSUE TITLE
Error when selecting action

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#71]
Hi @abyot ,
This morning I started to fill in the green box (category - thematic - type of support - action) and when I selected an action, the following pop-up came up (see screenshot). 

![image](https://cloud.githubusercontent.com/assets/21313941/20879238/12c71efa-bad3-11e6-8289-d69c6c64f23a.png)

Then when I moved on to the inventory year, the drop-down list was blank. I was able to select an agency but the year still had no options to choose from.

**Comment by abyot** [comment]
Hi @chloedenavit,

Must be a cache issue... working fine here.

![image](https://cloud.githubusercontent.com/assets/4967749/20879345/a20bb8e6-bad3-11e6-9415-2eea06978a80.png)

**Comment by chloedenavit** [comment]
OK, I got it to work.
