### ISSUE TITLE
problems with the Excel file

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#73]
Hi Abyot!
Our users sent us the first feedback on the Survey/Dashboard. Here the problems we found:

In the file Excel exported, in the "View data as table" section:

1. The UN Network’s is written “UN Networkâ€™s” – can we fix this?
2. The numbers (budget) show up strangely (see Sudan output 5.4.4.)
3. In the description box, the new paragraphs get deleted when we click on View Data as Table. 

- [x] Can we fix this (keep the paragraphs) or add a double slash (//) between each paragraph, or find another way to fix this?

**Comment by abyot** [comment]
- “UN Networkâ€™s” now appears "UN Network's" 

- The numbers issue is invalid

- Description box is new re-written. The system internally handles line-breaks and there is no need to insert  especial character. User's can proceed as normal and the system will handle the rest. Please test is and let me know if the issue still remains.

**Comment by chloedenavit** [comment]
Thanks @abyot , the UN Network's issue is solved. 

However for the line-breaks, I am not sure it worked. When I downloaded the data from Sudan, you can see in this screen shot that there is a string of symbols (Ã¢â‚¬Â¢) that are probably where the line breaks should have been. 

![image](https://cloud.githubusercontent.com/assets/21313941/21096536/a6ee8b76-c060-11e6-967c-ff6d9ceb7987.png)

**Comment by abyot** [comment]
Hi @chloedenavit ,

sorry, it is almost impossible to post-process the already entered data. The fix is for new entry...

**Comment by chloedenavit** [comment]
oh okay! Yes, when I tried a new country this worked well. Thanks!
