### ISSUE TITLE
Problem with the free text boxes

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#74]
- [ ] Several free text boxes seem to cut off the text (Kyrgyzstan Output 4.1.1 and Sudan Output 1.2.1 and Output 4.2.1). Just want to double check that this is their mistake and not the system cutting them off or losing the second half? 

- [ ] Is there a process in the system where our office can send a user a link to a specific question or output? 

This would help us direct them to specific ones that need to be reviewed.

**Comment by abyot** [comment]
This is not a problem from the system side. Currently there is no means to send comment / link to a specific question.
