### ISSUE TITLE
Question on staffing

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#75]
- [ ] Re-organize the order of the staff levels. Alphabetical order would be best (D1, D2, G..), except for  1) National REACH; 2) International REACH and 3) Cluster Coordinator.  These three that must be listed at the end.

**Comment by abyot** [comment]
It now alphabetical, if you wanted to do more ordering you can do it from here 
http://109.237.25.74:9091/inventory/dhis-web-maintenance/#/edit/categorySection/category/puKo3SraN2Q?_k=djezjd

**Comment by chloedenavit** [comment]
Perfect, thanks!
