### ISSUE TITLE
NOT required to fill out all of the joint programmes 

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#77]
We know that in theory (see Kyrgyzstan) all questions need to be answered in order to mark the report complete and leave the survey. However, for the question on the Joint Programmes, they do not need to fill in all the rows (e.g. if they have 7 Joint Programmes they don not need to fill in row 8 or row 9 with random data in order to not leave anything blank and mark the report complete).   

- [ ] Make sure that it is NOT required to fill out all of the joint programmes

**Comment by chloedenavit** [comment]
Hi @abyot,
Output 5.3.1.: I believe that for this output it is still being required to fill out all joint programmes. Are you able to change this so that only one joint programme (one ROW) must be filledo out? Of course this is only required if they mark YES to the previous question (5.3.1.).  Thanks!

**Comment by abyot** [comment]
yes, this one still remains to be fixed.

but I thought we agreed for at least one row to be filled instead of  "only one joint programme (one ROW) must be filled".

which one do you need?

**Comment by chloedenavit** [comment]
Yes, I think we are saying the same thing. At least one row must be filled. Thanks.

**Comment by abyot** [comment]
Fixed. Validation will pass if at least one cell is filled from the joint programme table.

**Comment by chloedenavit** [comment]
Thanks!

Could you remind me what the validation rule is for the staff tables and budget/expenditure tables (output 5.4) ?

**Comment by abyot** [comment]
The validation rule we have is that each question needs to be answered. For those questions with more than one answer - for example staff and budget questions - it is enough to have at least one answer (like filling at least one cell).

We just implemented an exception to "UN Joint Programme x" questions. Here, we are saying it is enough to answer one or more question. The rule, how a question can be answered, is the same everywhere. For those question with more than one value - it is enough to put at least one value.

**Comment by chloedenavit** [comment]
OK, I understand !

I have a question that I probably already know the answer, but I want to confirm : Would it be possible for the validation rule to require at least one cell PER COLUMN ? This way, we could make sure that every agency has filled at least one staff.  I am doubtful that this is possible, and that's ok, but just let me know if it is !

**Comment by abyot** [comment]
NO. That is too complex to implement.

**Comment by chloedenavit** [comment]
ok, no problem.
