### ISSUE TITLE
maximum number of characters 

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#78]
- [ ] As decided, in the free text boxes please set the maximum number of characters as 1500 (space included).

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
Thanks @abyot, this works well. 

Would it be easy for you to change the text to "Characters remaining: 1500" ? If not, please let me know how I can go in and edit it myself.

**Comment by abyot** [comment]
No, this is not something you (as a user) can configure. It is hard-coded in the system and I can change to your new suggestion.

**Comment by abyot** [comment]
Fixed.
