### ISSUE TITLE
question in Excel not included in the survey

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#79]
There is one question which doesn’t appear online, only on the Excel file downloaded : "Please briefly describe the UN Networkâ€™s involvement and activities this past year towards Output 5.4.4."

- [x] Why is it there in the Excel? Why didn’t it show up online?

**Comment by abyot** [comment]
The reason was, while adding / removing questions we haven't done it consistently between those assigned to "UN Network for SUN Annual Reporting" data set and the outcome group sets and out put groups.

This is now fixed.
