### ISSUE TITLE
pop-up mesages_report not complete

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#80]
The pop-up message that users receive if they have not answered to all questions is strange. The long list of questions included “undefined” in both the Outcome and the Outputs columns, and was not clear for the staff and financial questions.
Also, the list of questions does not follow the order they have in the survey. Output 5.5 should not appear  before Output 1.1
![capture on pop-up message not complete](https://cloud.githubusercontent.com/assets/22884743/20975648/5e61f532-bca0-11e6-952b-f88fc8cc953d.PNG)

See screenshot.

- [x] Can we make it better?

We can discuss about this.

**Comment by abyot** [comment]
Yes, looks better now. Fixed.

**Comment by chloedenavit** [comment]
Yes, thanks!
