### ISSUE TITLE
Compendium of Actions for Nutrition (icons and location of box)

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#83]
Hi @abyot,

I finally received the icons to replace the fake ones we used in the Inventory until now, but I realized there is actually 1 icon for every thematic area, not for every category. I decided to group them together so that there is still only one "button" for each Category. I developed a mock-up in PPT which I've converted to PDF. You'll find it in our shared drive : https://drive.google.com/drive/u/0/folders/0B0fAx5QYcDhmUHZldllLbGkydU0 

Then, we realized that it would make the most sense to have this orange CAN section at the top of the screen, since we want people to see it before they choose their Actions. Please take a look at my suggested format and let me know if this is possible? 

Once we agree on a format / organisation of the page and icons, I can send you the links.

**Comment by chloedenavit** [comment]
I also added the vector and JPEG versions of the icons to the shared folder!

**Comment by abyot** [comment]
Hmmm... that is a little tricky. 

We can group together the icons... a concern I have, though, is how they will look in different screen sizes... some of them might wrap, that affecting the text... might look ugly. But we will see, will try to block them together so that the icons stay together.

An easy solution is to group them together and take image ... that way we will be sure the all will stay together. An issue is how the resolution quality will look like...

As to the layout, sure we can put the CAN at the top... but seems the whole icon and drop down stuff will take a lot of space ... meaning users will have to scroll...

How about we consider 

1. the yellow left side column? I don't think we will be using the entire space for the sub-action?
2. introducing one more tab for the CAN?

**Comment by chloedenavit** [comment]
Hi @abyot,
Thanks for your feedback.

I'd rather not create a different tab for the CAN because it's not as easy to access.

I think the yellow left side column could work well, but I don't think we should include both the CAN _and_ the sub-actions in that same space. If we put the CAN in this column, I would suggest that we display sub-actions in a box below the Action Instance question. I know some of us were concerned that there wouldn't be enough space there, but I think that we can reduce the font size and maybe make the green box flexible, so that it expands only when there are a lot of sub-actions. I also think it is logical for sub-actions to be displayed immediately under the actions.  But this also would require scrolling ... But probably less than having that whole CAN-dedicated box with icons.

**Comment by chloedenavit** [comment]
Hi @abyot,
As a follow up: could you try to build the CAN as in my mock-up, using JPEG files, and then we can see if it takes up too much space? How much work will this be / time will it take?

If it's faster and easier, we could try putting the CAN in the yellow side column first, and the Sub-actions in the green box below Action Instance. 

Let me know what you recommend.

**Comment by abyot** [comment]
Hi @chloedenavit,

Here is a new layout

![image](https://cloud.githubusercontent.com/assets/4967749/21076623/63100c4e-bf30-11e6-916e-a49a4fddfab9.png)

**Comment by chloedenavit** [comment]
Hello, as we discussed:

- [ ] Make the font of the yellow side bar smaller (same size as text saying Category, Action, etc.)

- [ ] I will provide smaller versions of the buttons

- [ ] The blue box will take up less width (4) than the green space (8). 
In fact, can we also reduce the size of the left yellow column a little bit ? 

- [ ] The sub-actions box: 
- Change title of the box to: Replace the Thematic Area (here it was Livestock and Fisheries) with the word "Sub-Actions". 
- Could you also make the title of this box a smaller size? Maybe the size of "Category" and the size of the sub-actions can be one point smaller.
- Remove the white background behind the actions
- minimize the space between each line so that the whole list takes up less space.

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
Thank you, this looks great! Will work on the buttons today... it's a bit difficult to maintain the quality and ensure they're all aligned and spaced the same way since I don't have any design software or skills. I am trying to use PPT but the quality is low, but I suppose that's okay.

**Comment by abyot** [comment]
I thought you had the graphics designer...

**Comment by chloedenavit** [comment]
Her contract is finished. It took her a long time to produce the icons in JPG and vector format for us, so I was asked not to request any more of her time.

**Comment by chloedenavit** [comment]
Hi @abyot,

Here are the links for the CAN buttons:

Full CAN (underlined in the paragraph of text above the buttons): 
http://www.reachpartnership.org/documents/312104/fa572e1e-b8a9-48bf-89c0-cd3afb203c60

Food, Ag, Healthy Diets: 
http://www.reachpartnership.org/documents/312104/647fc812-274b-4028-a36e-bf78a4e7c008

Maternal and Child Care:
http://www.reachpartnership.org/documents/312104/b58a5c8e-4989-4f1a-81fb-57ae850abd63

Health:
http://www.reachpartnership.org/documents/312104/0c8e3dfd-a1f2-4678-a340-0050ef54290d

Social protection: 
http://www.reachpartnership.org/documents/312104/8df9b5e7-1452-4e40-ae83-b8b4e6cc9e23

MS nutrition governance: 
http://www.reachpartnership.org/documents/312104/7ce1820e-cdbd-42ad-84a8-24872d8db2cd

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
perfect, thanks.
