### ISSUE TITLE
Additional box for links

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#84]
Hi @abyot, 
In the Dashboard could you please add a box next to the green one (see attached document) with the following text and links:

UN Network for SUN Resources:
- User Manual
- [UN Network for SUN Tools and Resources](http://scalingupnutrition.org/sun-supporters/un-network-for-sun/)
- [UN Network for SUN Strategy (2016-2020)](http://docs.scalingupnutrition.org/wp-content/uploads/2016/11/UN-Network-for-SUN-Strategy-2016-2020.pdf)

I hope these hyperlinks will work. I have no added a hyperlink for the manual yet as it isn't finished.

[Dashboard mock up.pdf](https://github.com/abyot/sun-inventory/files/640101/Dashboard.mock.up.pdf)

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
Looks great, thanks! However I only see it when I use the inventory link, and then access the dashboard App through the App menu. 

Have you integrated the two systems?

**Comment by abyot** [comment]
It should be a cache issue, otherwise I have updated the dashboard system as well.
