### ISSUE TITLE
Dashboard and Inventory Icons

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#85]
Hi Abyot,
thanks a lot for changing the Dashboard and Inventory icons. Unfortunately we noticed that, being in black, they do not fit with the other icons in the App menu - they are too black. 

- [ ] Could you please send us a link with colorful icons so that we can tell you which ones we like?
If you already have something similar to the icons we already chose, but in color, that would be fine too!
thanks
Alisia

**Comment by abyot** [comment]
hmm... I don't think that is a good approach. Instead of me picking color and sending it for your approval and back and forth, just let me know a color of your choice and I can give the icons the same color.

**Comment by Alisia1** [comment]
the things is, we don't want the icons to be all blue or all red, we'd like something similar to the icons we already have (like the Reports app) - unless you can colour the icons in different nuances, like red/yellow/green?
Do you have a list of colorful icons among which we can choose - like the link you sent us already, but instead of having only black icons, with colorful ones.
thanks!

**Comment by chloedenavit** [comment]
Hi @abyot, just to contribute to what Alisia said: the issue is not the color but the fact that the icons we chose are not in the same "style" as the ones that already exist in the Apps menu. We want our Apps to blend in and seem like a natural part of the Apps menu.

**Comment by abyot** [comment]
ok, now I get you.

but it is two different things... what we have earlier was more like an image. You can choose for a free ones from here if you are  going some artistic stuff.  

https://www.iconfinder.com/ 

search for something for example pie  chart

https://www.iconfinder.com/search/?q=pie+chart

and choose for free ones. You can also search for list

https://www.iconfinder.com/search/?q=list

The last time you asked me - when you send me specific icons/links - it was icon/text/vector image. I can give any color to it (but only a one color - full red, blue or whatever) but not sort of artistic stuff with blend of colors.

**Comment by chloedenavit** [comment]
OK great, thanks! We will choose from this list.

**Comment by Alisia1** [comment]
Hey Abyot,
please use the icons at this link https://www.iconfinder.com/iconsets/xomo-basics
Here a screenshot of those we want:

- Number 1 for the Inventory
- Number 2 for the Dashboard

![capture new icons dashboard and inventory](https://cloud.githubusercontent.com/assets/22884743/21050182/7f439574-be19-11e6-8828-551031ad1062.PNG)

thanks!

**Comment by abyot** [comment]
Done.
