### ISSUE TITLE
Paragraph with instructions for IT

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#86]
Hi @abyot,
This is a reminder to ask if you could please write some short instructions about: 1) the minimum IT set-up needed for a user to access the Dashboard and Inventory; and 2) What steps they (OR their IT colleagues) should follow if they cannot access the website when they click on the link. 

We can put these instructions in the manual and also send them by email if they encounter problems.

Thanks!

**Comment by chloedenavit** [comment]
Hey @abyot,
Just a reminder : On our last call you said that you would forward me the information you sent to Kris because I was not able to find it here. Thanks!

**Comment by abyot** [comment]
There is nothing much to setup, one just needs a browser (preferably Google Chrome) and Internet connection. This of course is based on the assumption that the server is deployed and up and running. DHIS2 has documentation on how to deploy a server. See the documentation (https://ci.dhis2.org/docs/master/en/implementer/html/dhis2_implementation_guide_full.html) for more details.

Depending on how the server is deployed, there could be some tweaks that one should do to ensure network access. A typical situation to look into is to make sure the port, the server is running on, is not blocked by firewalls and other network protecting devices across the client network. 

For example, the demo instances are running on the following ports (note: these ports are arbitrary and vary depending on deployments)

1. SUN PMT port 9090 
    http://109.237.25.74:9090/sunpmt/dhis-web-commons/security/login.action
2. UN Network for SUN Reporting port 9091
    http://109.237.25.74:9091/inventory/dhis-web-commons/security/login.action
3. UN Nutrition Inventory port 9595
    http://109.237.25.74:9595/unnutritioninventory/dhis-web-commons/security/login.action

These ports should not be blocked for the servers to be accessible.

**Comment by chloedenavit** [comment]
Thanks, this helps a lot. Once our WFP server is up and running, I will need the new port information (maybe from you or from WFP) so that I can put them in the manual to help field-based IT Colleagues.
