### ISSUE TITLE
Name of App

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#87]
Hi @abyot, could you please change the name of the App to UN Network for SUN Reporting -- right now the App in the menu is called UN Network for SUN Dashboard.

**Comment by abyot** [comment]
ok, will change it ... but it was you who named it like that

![image](https://cloud.githubusercontent.com/assets/4967749/21101746/eca0b350-c07a-11e6-85de-fd5b55b2ae67.png)

**Comment by chloedenavit** [comment]
Yes, that was in September before we had realized that Dashboard was not a good name. We really do appreciate your flexibility!!

**Comment by abyot** [comment]
Fixed.
