### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#91]
Just a reminder to please email me the lists of translations that we need to do for the Inventory and Dashboard. Thanks!

**Comment by abyot** [comment]
Inventory:

- https://raw.githubusercontent.com/abyot/sun-inventory/master/dhis-web/dhis-web-apps/src/main/webapp/dhis-web-action-inventory/i18n/i18n_app.properties 

Dashboard:

- https://raw.githubusercontent.com/abyot/sun-inventory/master/dhis-web/dhis-web-apps/src/main/webapp/dhis-web-sun-survey/i18n/i18n_app.properties
