### ISSUE TITLE
filter empty rows

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#92]
Could you please change this to "Hide empty rows" and make the check box bigger? I'm not sure it will look good to have a button, but whatever you think will make it more visible (and still look nice) would be great.

**Comment by abyot** [comment]
![Uploading image.png…]()

**Comment by chloedenavit** [comment]
Thanks! 

- [ ] Could you please change the Hide button to blue? 

- [ ] The PDF button looks a bit lonely under the blue box. Could we perhaps list all the buttons together, under the blue box where the PDF is now?  
The order of placement could be:
View data as table - Hide empty Rows - PDF

**Comment by abyot** [comment]
:) ok.

But it is excel not pdf... just in case you are thinking along the line of pdf.

**Comment by chloedenavit** [comment]
oops, sorry, I know it is excel !

**Comment by abyot** [comment]
sure. just wanted to avoid another back and forth of change this and that.

I mean, seems you have very specific ideas/plans how things should look like and I would be happy if you could provide them before hand. That way will save us lots of time.

**Comment by chloedenavit** [comment]
I'm sorry, I try to be better at that. 
Here is a mock-up of what I am picturing for this change:

![slide1](https://cloud.githubusercontent.com/assets/21313941/21307344/6f41286c-c5d5-11e6-8b67-87a22d947006.JPG)

**Comment by abyot** [comment]
We have the complete button coming as well... 

Of course your decision, but I suggest for "View data as table[GREEN]" and "Mark report complete [BLUE]" to be on the same row next to the blue box. We can have the excel and filter buttons on the same row underneath the blue box.

For the filter - I can use this [icon](http://fontawesome.io/icon/filter/) if it is important to have both export and filter to be icons. Another option is, to convert both (export and filter) to buttons ... the last option is to use icon for excel and button for filter. You can decide.

**Comment by abyot** [comment]
Changed to buttons.

**Comment by chloedenavit** [comment]
Looks good, thanks!
