### ISSUE TITLE
Feedback on reports

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#93]
Here is what we discussed about the feedback I sent on the reports (these are based on comments I sent by email - please refer to that): 

Reports you will create: 
- [x] Region slides: You will create this one, with all the regions included in one table.
- [ ] Align invest: You are working on this in the Special Reports
- [x] Which Aligned: Please use my new table which I uploaded into our Shared Drive, called "New Report Suggestion". You said this was doable.
- [x] Nut Explicit: Could you also make a new table listing all the actions that were marked as _not nutrition explicit?_
- [x] Nut Explicit: Could you also make a new table listing all the actions that were marked as _not aligned to national country plans?_ 

Reports you will try to create but not priority:
- [x] LogoMap_Agencies: You will try to make this in a Special Report but it is not priority.
- [x] Number of agencies: You will try to make this in a Special Report but it is not priority.

Discussions in my email that we solved on the call - that need no further action:
- Category Slide: Fine
- National level: You showed me how to do this- Fine.
- Joint programme 2: We think there is hidden data that was entered at non-national level.

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
I reviewed all the reports and they all look good - thank you so much.

Quick question: Can you remind me how the data is collected for "action conducted"? Is this collected when users click "save" for an action instance they have filled out ?

**Comment by abyot** [comment]
That is more like internal... I can explain during the call tomorrow.
