### ISSUE TITLE
question warning font

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#94]
Hi @abyot,
In the Dashboard, the "question warning" really takes up a lot of space, almost the amount of 4 sub-questions. I was wondering if we could reduce that by:
- reducing the font (to be the same size as the sub-questions, and not bold)
- reducing the margins: Right now there is a large margin around the text and another margin around the yellow warning box. Can we reduce the margin around the text (the size of the pale yellow background box)? 

Let me know if this is not clear.

**Comment by abyot** [comment]
Fixed.

**Comment by chloedenavit** [comment]
Looks good, thanks!
