### ISSUE TITLE
Question modification

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#96]
Hi Abyot,
I have added 4 questions to output 1.1.1 and modified others,  and everything has worked except for 2 issues:

1. I have created 4 new questions and have added them to Data Element Group, but they are not showing up. The questions are:
Please indicate which partners were engaged in completing other nutrition analyses
(and 3 more like this, with different endings)

2. I would like to use the Category "Partners" for the answer options, but add a new I cannot see it in the list when I am in the question definition. Must I follow another step before it appears there? Or do I need to create a new list?

In addition, 
- Could you tell me how to make these questions multiple select? Is it by checking "Dimension as Multi option set" or is it done by choosing Display Mode- multi option?

Thank you!
Chloe

**Comment by abyot** [comment]
The drop-down was introduced later when we had that Joint programme thing... I am thinking to kind of merge the two at some point. 

For now, use checkbox "Dimension as multi option set".

Use the following steps to add a new question:

1. create the question first - with mode, order and related stuff properly configured
2. assign it to the proper output (which is data element group)
3. assign it to data set "UN Network for SUN Annual Reporting"

**Comment by chloedenavit** [comment]
Thanks, I was missing step 3.

As for the drop-down, what would you recommend that I do? Should I create a new list?

**Comment by chloedenavit** [comment]
Great, this all worked. Closing the issue!
