### ISSUE TITLE
Limit number of characters in a numerical question

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#97]
Hi @abyot 
I "unhid" a question and I would like to limit the number that people can enter as an answer. Maximum should be 10. 

The question is: "
Please indicate the number of joint UN nutrition programmes in place and currently being implemented" in
Otuput 5.3.

Could you tell me if I can set this maximum myself? I checked the DHIS2 manual but could not find this information.

**Comment by abyot** [comment]
Hi @chloedenavit,

No, it is not possible to do that at configuration level. Setting that as part of the metadata definition is totally a new set of design process.

**Comment by chloedenavit** [comment]
OK, then we can leave it without a limit if that is complicated to do. 
Thanks
