### ISSUE TITLE
Change "Category" to "Section" 

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#98]
Hi @abyot,
We have been asked to rename "Category" to "Section" in order to match new CAN documentation being written. Could you instruct me on how to change this in the system, for the green box? Are there other places I should change it in the metadata? Please let me know how I can help. I can change the names of the Reports manually.

**Comment by abyot** [comment]
No this is something hardcoded in the system, we do not have a metadata configuration for this.

Fixed.

**Comment by chloedenavit** [comment]
Thank you! 

However, now when I scroll over the information icon, it says "CAN_review_info". When you fix this, could you check if the previous definition I had sent you said Categories? If it does, could you replace this with Sections?

**Comment by abyot** [comment]
Thanks for pointing that ... fixed now.

**Comment by chloedenavit** [comment]
Great. Could just change "right" to "left" as the yellow menu is on the left side of the screen now?

**Comment by abyot** [comment]
sure, will change that... this was the thing I wanted to avoid when being very explicit and at the same time keep changing.
