### ISSUE TITLE
Please indicate the geographic focus of this action instance

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#99]
Hi @abyot,
We noticed that now that the CAN section is taking up a lot of space in the left hand column, the definition for the question "Please indicate the geographic focus of this action instance" is taking up a lot of space and doesn't look good. 

Is it possible to make the definition show up across the whole width of the question and answer columns? Here's a screen shot to explain what I mean. 
![screenshot](https://cloud.githubusercontent.com/assets/21313941/21177608/3430b75c-c1ec-11e6-8ef1-919169dcb0ed.png)

If this isn't possible, could you suggest any other solution? 

I know that one solution is to cut down the definition and put the extra information in the manual, but I don't think that everyone will read the manual in detail so that's not the best option in my opinion.

**Comment by abyot** [comment]
Fixed

**Comment by chloedenavit** [comment]
Looks good, thanks!
